[Week1] Create Todo REST API
CodeSoom/spring-week1-assignment-1 pull request #4
Opened 2021-01-18 13:32 UTC by JamieShin0201

# Todo
- [ ] ToDo 목록 얻기 - GET /tasks
- [ ] ToDo 상세 조회하기 - GET /tasks/{id}
- [ ] ToDo 생성하기 - POST /tasks
- [ ] ToDo 제목 수정하기 - PUT/PATCH /tasks/{id}
- [ ] ToDo 삭제하기 - DELETE /tasks/{id}

안녕하세요^^
서버, 핸들러만 생성하고 먼저 PR 보냅니다.
계속 과제 진행하겠습니다.

2021-01-19 13:23 UTC, JamieShin0201 commented
안녕하세요^_^

1. Repository에서는 Task에 대한 id 자동생성후 저장하는 역할을 하도록 구현하였습니다.
2. Service에서는 Repository에 저장하라는 요청을 보내고 성공, 실패 여부를 처리하도록 구현하였습니다.
3. Handle에서는 HTTP 요청에 따라 알맞는 service메서드를 실행시켜주도록 구현하였습니다.

handle부분에 코드가 지저분하여 전반적으로 수정해야할 것 같고
잘못된 요청에 따른 처리를 추가해야할 것 같습니다.
계속 진행하도록 하겠습니다!

감사합니다 ㅎ.ㅎ

2021-01-19 15:44 UTC, hannut91 requested changes
고생하셨어요 ㅎㅎ

2021-01-19 15:44 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        }
if절이 너무 복잡해 보이네요. `if`나 `switch`없이 구현할 수 있을까요?
객체지향 생활체조에서는 `else`를 사용하는 것을 금하고 있습니다.

See also
  - https://developerfarm.wordpress.com/2012/02/03/object_calisthenics_summary/

2021-01-19 15:44 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +            }
`isDeleted`가 `false`면 어떻게 되나요?

2021-01-19 15:44 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +            }
`content`가 있으면 이라고 읽는게 더 자연스러울 것 같아요. 지금은 `content`가 빈 문자열이 아니면으로 읽히고 있어요.

2021-01-19 15:44 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        return Long.valueOf(identities[2]);
왜 `2`인지 파악하기 어려운 것 같아요

2021-01-19 15:44 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/utils/JsonParser.java
> +        }
여기서 catch해버리면 이 메서드를 사용하는 곳에서 무슨 일이 일어나는지 모르게 돼요.

2021-01-19 17:40 UTC, JamieShin0201 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        }
요청메서드에 따라서 처리하는 로직을 분리하긴 했는데.. switch문을 사용했네요..
switch, if 없이 구현하는 법은 고민해보겠습니다!!

2021-01-19 17:43 UTC, JamieShin0201 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +            }
false일때는 default(Not found code) 가 되도록 했는데 명시적인게 더 보기 좋을 거 같습니다.!

2021-01-19 17:47 UTC, JamieShin0201 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +            }
isEmpty 메서드를 사용해서 조금 더 가독성있게 수정했습니다 ㅎㅎ

2021-01-19 17:48 UTC, JamieShin0201 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        return Long.valueOf(identities[2]);
```
Long id = Long.valueOf(path.replace(TASKS + "/", ""));
```

이렇게 작성하는건 괜찮을까요?

2021-01-19 17:49 UTC, JamieShin0201 commented on app/src/main/java/com/codesoom/assignment/utils/JsonParser.java
> +        }
예외처리하는 부분은 제가 조금 더 공부를 해야할거 같습니다. ㅠㅠ catch에서 에러를 던지도록 수정했습니다!

2021-01-20 14:53 UTC, JamieShin0201 commented
switch, if 를 사용하지 않으려고 enum을 활용했는데요! 
이게 괜찮은지는 조금 더 고민해보겠습니다!

2021-01-20 16:56 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        }
리퀘스트가 유효한 리퀘스트인지 확인하는 책임은 누가 가져야 하나요?

2021-01-20 16:56 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/models/HttpRequestMethod.java
> +    GET((httpRequest, taskService) -> {
`enum`에 이렇게 lambda를 넣을 수 있군요!

2021-01-20 18:21 UTC, JamieShin0201 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        }
HttpRequest에게 책임이 있는 거 같아 수정하였습니다 ㅎ.ㅎ

2021-01-20 19:05 UTC, JamieShin0201 commented
1. HttpStatus를 enum으로 변경하였습니다.
2. HttpRequest를 추상클래스로 변경하고 그 구현체로 HttpRequestForTasks를 만들었습니다.
3. HttpRequestForTasks 클래스 안에 request 유효성 체크를 했습니다.

감사합니다 ㅎ.ㅎ

2021-01-21 05:05 UTC, JamieShin0201 commented
1.  HttpRequestProcessor 라는 인터페이스를 만들어서 그 구현체로 TaskHttpReuqetMethod를 만들었습니다.
2. DemoHttpHandle를 TasksHttpHandler로 이름을 변경하고 /tasks 경로만 처리하도록 하였습니다.

2021-01-21 14:27 UTC, ahastudio commented on app/src/main/java/com/codesoom/assignment/utils/IdGenerator.java
> +        return id;
getter처럼 보이는데 상태를 변경하는 건 객체를 사용하는 쪽에서 오해할 소지가 있습니다. getter처럼 보이지 않으면 좋을 것 같아요.

2021-01-22 09:14 UTC, JamieShin0201 commented on app/src/main/java/com/codesoom/assignment/utils/IdGenerator.java
> +        return id;
그러네요. 새로운 아이디를 생성한다는 의미가 들어가도록 수정하면 좋을거 같네요 ㅎㅎ

2021-01-22 12:11 UTC, JamieShin0201 commented on app/src/main/java/com/codesoom/assignment/TasksHttpHandler.java
> +        if (!exchange.getRequestURI().getPath().startsWith(TasksHttpRequest.TASKS)) {
TASKS 상수를 어디에 옮길까 고민을 많이 해봤는데.. 
HttpServer가 path와 handler를 가지고 context를 만드니 HttpServer를 이용하는 클래스(App) 가 TASKS상수를 책임 지는게 맞는거 같습니다.
상수를 private하게 바꾸려하니 전반적으로 잘못된 설계들이 보여 코드를 많이 수정해야할 것 같네요!

2021-01-22 12:20 UTC, ahastudio commented on app/src/main/java/com/codesoom/assignment/TasksHttpHandler.java
> +        if (!exchange.getRequestURI().getPath().startsWith(TasksHttpRequest.TASKS)) {
아, 저는 오히려 메서드만 노출하고 상수를 숨기는 걸 제안한 거예요. 예를 들어 `taskHttpRequest.handle(exchange)` 같은 식으로 사용하고, 세부 처리를 그쪽으로 떠넘기면 어떨까요?

2021-01-22 13:00 UTC, JamieShin0201 commented on app/src/main/java/com/codesoom/assignment/TasksHttpHandler.java
> +        if (!exchange.getRequestURI().getPath().startsWith(TasksHttpRequest.TASKS)) {
아... 좋습니다!! 제가 생각을 잘못 했네요..
taskHttpRequest에서 해당 로직을 수행하면 상수를 숨길수 있겠네요! 감사합니다ㅎㅎ

2021-01-22 13:49 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/models/TasksHttpRequest.java
> +    public static final String TASKS_PATTERN = TASKS + "/*[0-9]*";
`/tasks/*[0-9]*`이 정규식은 `/tasks///10`도 걸리기 때문에 잘못될 수 있을 것 같아요

2021-01-22 13:49 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/service/TaskService.java
> +        }
`tasks.isEmpty()`를 사용하는 것은 어떨까요?

2021-01-22 14:06 UTC, ahastudio commented on app/src/main/java/com/codesoom/assignment/repository/TaskRepository.java
> +    public static TaskRepository getInstance() {
구글에서 `singleton is evil` 등을 검색해 보세요.

2021-01-22 16:55 UTC, JamieShin0201 commented on app/src/main/java/com/codesoom/assignment/models/TasksHttpRequest.java
> +    public static final String TASKS_PATTERN = TASKS + "/*[0-9]*";
그러네요!! 
**/tasks/[0-9]*** 로 변경하였습니다 ㅎㅎ

2021-01-22 16:55 UTC, JamieShin0201 commented on app/src/main/java/com/codesoom/assignment/service/TaskService.java
> +        }
훨씬 더 명확한 것 같습니다! ㅎㅎ

2021-01-23 18:41 UTC, hannut91 approved these changes
객체지향에 대해 더 고민해보시면 좋을 것 같아요 ㅎㅎ
그리고 스프링을 사용했을 때는 어떤 부분이 좋아지는지도 같이 고민하면 좋을 것 같아요
고생하셨어요 ㅎㅎ 

회고를 작성해주시면 머지하겠습니다!

2021-01-23 18:41 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/TasksReflection.java
> +        }
`matchedMethod.isEmpty`를 사용하는 것은 어떨까요?

2021-01-23 18:41 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/utils/JsonParser.java
> +    }
문자열을 Task로 매핑하는데 실패할 수 있는 경우가 있어요. 근데 그럴 때 null을 돌려주는 것은 결국 사용하는 곳에서 `null`을 확인해야 할거에요. 다음과 같이 바로 반환하고 사용하는 곳에서 예외를 적절하게 처리할 수 있도록 하는게 좋을 것 같아요. 지금과 같이 이미 발생할 수 있는 경우를 잡아서 다른 예외를 던지게되면 무슨 일이 일어나는지 파악하기 어려울거에요

```java
return objectMapper.readValue(content, Task.class);
```

2021-01-23 22:18 UTC, JamieShin0201 commented on app/src/main/java/com/codesoom/assignment/TasksReflection.java
> +        }
조건문에는 가능하면 부정문보다는 긍정문을 써야하는데 자꾸 실수를 하네요..! ㅠㅠ

2021-01-23 23:22 UTC, JamieShin0201 commented
> 객체지향에 대해 더 고민해보시면 좋을 것 같아요 ㅎㅎ
> 그리고 스프링을 사용했을 때는 어떤 부분이 좋아지는지도 같이 고민하면 좋을 것 같아요
> 고생하셨어요 ㅎㅎ
> 
> 이번 과제를 통해서 무엇을 배우셨나요?

2021-01-24 04:07 UTC, closed without merging