첫주차 과제 일부 작성
CodeSoom/spring-week1-assignment-1 pull request #43
Opened 2021-08-09 11:58 UTC by ytkim4558

2021-08-09 12:15 UTC, johngrib reviewed
반갑습니다. 한 주 힘내서 열심히 학습해 봅시다 :-)

2021-08-09 12:15 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/App.java
> +            InetSocketAddress address = new InetSocketAddress(8000);
매직 넘버인 포트 넘버 `8000`이 눈에 띄는군요. 매직 넘버를 분리해서 메소드 바깥으로 꺼내고 적절한 이름을 붙여보면 어떨까요?

2021-08-09 12:15 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/App.java
> +            HttpServer httpServer = HttpServer.create(address, 0);
마지막의 `0`은 어떤 의미를 갖고 있나요? 설명해보실 수 있을까요? 만약 설명할 수 없다면 조사해서 설명해 주세요. :-)

2021-08-09 12:15 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +import java.io.*;
`import *`은 편리하지만 좋지 않은 습관입니다. 가급적이면 내가 어떤 것을 import하는지 명확히 알아두는 습관을 갖는 것이 좋습니다. `import *`을 해제하고 여러 줄 `import`로 바꾸어 보시면 어떨까요?

2021-08-09 12:15 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        }
body 가 비어 있을 때 `println`으로 출력을 하면 어떤 결과가 나오나요?

2021-08-09 12:15 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        }
`method.equals("GET")` 과 같은 코드는 별다른 문제가 없어 보이지만 `method`가 `null`인 경우에 Null Pointer Exception이 발생할 수 있는 위험이 있습니다.

`"GET".equals(method)`와 같이 바꾼다면 이런 위험을 미연에 방지할 수 있어요.

2021-08-09 12:15 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        httpExchange.sendResponseHeaders(200, content.getBytes().length);
이 `200`이 어떤 의미인지 설명이 가능한가요? 만약 설명이 가능하다면 `200`이 공식적으로 선언된 곳이 어디인지도 조사해 보세요.

2021-08-09 12:44 UTC, ytkim4558 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        }
body가 비어있으면 조건문에 들어가지 않아서 실행이 안되지만 위의 조건문을 무시한다고 하면 아무것도 안찍히고 한줄 비어진상태로 출력됩니다

2021-08-09 12:50 UTC, ytkim4558 commented on app/src/main/java/com/codesoom/assignment/App.java
> +            InetSocketAddress address = new InetSocketAddress(8000);
portNum 으로 변수로 빼겠습니다

2021-08-10 11:46 UTC, ytkim4558 reviewed
의견주신 내용 반영 + 과제 내용 반영했습니다. 
이 200이 어떤 의미인지 설명이 가능한가요? 만약 설명이 가능하다면 200이 공식적으로 선언된 곳이 어디인지도 조사해 보세요
의 부분은 조사해봤으나 설명된곳을 못찾겠습니다

2021-08-10 11:46 UTC, ytkim4558 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +import java.io.*;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
로 변경했습니다

2021-08-10 11:47 UTC, ytkim4558 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        httpExchange.sendResponseHeaders(200, content.getBytes().length);
해당부분 찾아봤으나 잘 못찾겠습니다;

2021-08-10 11:48 UTC, ytkim4558 commented on app/src/main/java/com/codesoom/assignment/App.java
> +            HttpServer httpServer = HttpServer.create(address, 0);
이 부분도 찾아보려 했으나 내장함수 형태라 그런지 클릭해서 찾을수 없고 검색해도 딱히 특별하게 설명된곳을 못찾겠습니다; 어떻게 찾으면 좋을까요?

2021-08-10 12:25 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/App.java
> +            HttpServer httpServer = HttpServer.create(address, 0);
여러 가지 방법이 있는데요, 그 중 가장 쉬운 방법은 IntelliJ 에서 `create` 메소드를 `control+클릭`(맥에서는 `command+클릭`)하는 것입니다. 그러면 소스코드와 javadoc 문서를 볼 수 있습니다. 또는 `HttpServer` 클래스의 javadoc을 인터넷에서 찾아보는 것이 있습니다.

다음 링크를 찾아내면 성공입니다.
https://docs.oracle.com/javase/8/docs/jre/api/net/httpserver/spec/com/sun/net/httpserver/HttpServer.html

2021-08-10 12:26 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +import java.io.*;
conversation resolve는 직접 하지 마시고 제가 하도록 할게요. 여러 사람의 리뷰를 하다 보면 어떤 대화가 끝났고 안 끝났는지가 헷갈리거든요. 직접 닫으시면 제가 대화가 끝난 줄 알고 추가로 힌트 드리는 걸 깜빡하고 지나가거나 할 수 있습니다.

2021-08-10 12:27 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        }
네 그렇다면 저 코드는 `body`가 비어있다는 사실을 콘솔에 표시하기 위해 넣으신 거겠지요? 그렇다면 훨씬 세련된 메시지를 출력하시는 것도 고려하실 수 있을 거에요.

2021-08-10 12:28 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        httpExchange.sendResponseHeaders(200, content.getBytes().length);
이럴 땐 RFC 문서를 찾아 읽으셔야 합니다. 반드시 기억해 두세요.

https://datatracker.ietf.org/doc/html/rfc2068

2021-08-10 12:31 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        URI uri = httpExchange.getRequestURI();
URI는 무엇의 약자인가요?

2021-08-10 12:31 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        String[] pathElements = path.split("/");
여기에서는 `path`가 `null`이라면 NPE가 발생할 것입니다. 어떻게 대처해야 좋을까요?

2021-08-10 12:31 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        else if("GET".equals(method) && pathElements.length > 2) {
이렇게 `}`과 `else if`를 떼어 놓는 방식은 흔히 볼 수 있는 자바 코드의 컨벤션과는 차이가 있습니다. 중괄호와 `else`를 한 줄에 작성해 주세요.

2021-08-11 12:16 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +            httpExchange.sendResponseHeaders(httpStatusCode, length);
http method별로 각각의 처리 코드를 private 메소드로 분리해 보세요. 한결 읽기 좋아질 거에요.

2021-08-11 12:16 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +                ++id;
`id`를 이렇게 증가시킬 때의 문제점은 무엇이 있을까요? 생각해 보세요.

2021-08-12 13:02 UTC, ytkim4558 commented on app/src/main/java/com/codesoom/assignment/App.java
> +            HttpServer httpServer = HttpServer.create(address, 0);
코멘트 테스트입니다.

2021-08-12 13:34 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        URI uri = httpExchange.getRequestURI();
이럴 때에는 꼭 RFC 문서도 읽어 주세요.

https://datatracker.ietf.org/doc/html/rfc3986

2021-08-12 13:34 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +            httpExchange.sendResponseHeaders(httpStatusCode, content.getBytes().length);
이렇게 각 HTTP method를 처리하는 코드를 private method로 분리해 보세요. `GET`처리기 하나, `POST` 처리기 하나... 이렇게 분리해보면 적절하겠죠.

2021-08-12 13:34 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/models/HttpStatusCode.java
> +    }
아직까지는 문제 없습니다. 다만 HTTP status는 엄청나게 많으니 그것에 대한 고민도 한번쯤 해보실 필요가 있어서 남긴 말이에요. `enum` 순회에 대한 방법을 충분히 고민해 보시고 다양하게 시도해 보세요. 그리고 나서 다른 사람들은 어떻게 하는지도 검색해 보세요.

2021-08-13 11:31 UTC, ytkim4558 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +    private HashMap<Long, Task> tasks = new HashMap<>();
사실상 당장은 Task의 id의 역할이 없네요 hashmap의 id를 할당할때 taskmap의 id도 같은 값으로 할당은 하지만 쓰고있지는 않습니다.

2021-08-13 11:33 UTC, ytkim4558 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +    private HashMap<Long, Task> tasks = new HashMap<>();
아니네요 getTasks할때도 그렇고 task 가져올때 해당 task 내용을 출력할때 등 필요하네요 말씀하신것처럼 다른 역할로 사용되는것이네요

2021-08-13 12:48 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +import java.io.*;
여기 아직 변경 작업이 이루어지지 않은 것 같아요.

2021-08-13 12:48 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        httpExchange.sendResponseHeaders(httpStatusCode, length);
잘 작업하셨습니다. 그런데 `getTasks()`, `generateTask(body)` 등이 메소드 스코프를 넘어서는 전역 변수를 사용하는 것이 아쉽습니다. 더 나은 방법을 고민해 봅시다.

2021-08-13 12:48 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +            ++id;
코드 한 줄 밖에 안 되지만, 이 한 줄은 아이디를 증가시키는 책임을 갖고 있습니다. 즉 이 메소드 내에서는 다양한 책임이 혼재되어 있어요. 할일 생성과 아이디 생성이 대표적이죠. 아이디 생성과 증가를 책임지는 객체 하나를 만들어서 책임을 분리해보면 어떨까요?

2021-08-13 12:48 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +    }
가급적이면 `tasks`를 직접 사용하지 않고 메소드 파라미터로 입력받아 사용하는 방향으로 작업해 봅시다.

2021-08-13 16:13 UTC, ytkim4558 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +import java.io.*;
idea가 자동으로 최적화한답시고 푸시직전에 저리 바꾸네요;;

2021-08-15 12:32 UTC, johngrib reviewed
한 주간 고생 많으셨습니다. 주간 회고를 작성해 슬랙에 올려주세요. 주간 회고를 작성하셔야 머지를 해 드려요.

2021-08-15 12:32 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        }
이 부분 코드가 전반적으로 어수선합니다. `if`문 안쪽의 조건문은 private 메소드로 분리하는 것을 고려하시고, 각 `if`문 block 내의 코드도 다른 메소드로 분리해보세요.

2021-08-15 12:32 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        } else {
윗줄에 있는 `if` 블록에 `return`하는 코드를 추가한 다음, `else` 키워드를 제거해 보세요.

2021-08-16 11:56 UTC, johngrib requested changes
PR merge 대상 브랜치가 `CodeSoom:main`으로 잘못 지정되어 있습니다. `Edit` 버튼을 클릭하면 수정할 수 있으니 수정해 주세요.

![image](https://user-images.githubusercontent.com/1855714/129559999-c80d1c1f-a655-4510-b213-189773641603.png)

2021-08-16 12:45 UTC, ytkim4558 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        }
전역변수부분을 바깥으로 빼려다보니 다시 어수선해졌는데 좀더 고민해볼게요..

2021-08-16 12:46 UTC, ytkim4558 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        } else {
> PR merge 대상 브랜치가 `CodeSoom:main`으로 잘못 지정되어 있습니다. `Edit` 버튼을 클릭하면 수정할 수 있으니 수정해 주세요.
> 
> ![image](https://user-images.githubusercontent.com/1855714/129559999-c80d1c1f-a655-4510-b213-189773641603.png)

지금처럼 수정하면 될까요 어느 브랜치로 할지 몰라 찾아봤는데 제 아이디로 된게 있어서 거기로 변경했습니다

2021-08-16 13:36 UTC, ytkim4558 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +            httpExchange.sendResponseHeaders(httpStatusCode, length);
작업했습니다!

2021-08-16 13:37 UTC, ytkim4558 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +            httpExchange.sendResponseHeaders(httpStatusCode, content.getBytes().length);
해당 방법으로 작업다시 햇습니다

2021-08-16 23:13 UTC, ytkim4558 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +    }
메소드로 받아 처리하는 방법으로 변경했습니다

2021-08-17 12:08 UTC, merged