1주차 과제
CodeSoom/spring-week1-assignment-1 pull request #5
Opened 2021-01-18 13:40 UTC by etff

## 🎯 요구사항
 * []  1. ToDo 목록 얻기 - GET /tasks
 * []  2. ToDo 상세 조회하기 - GET /tasks/{id}
 * []  3. ToDo 생성하기 - POST /tasks
 * []  4. ToDo 제목 수정하기 - PUT/PATCH /tasks/{id}
 * []  5. ToDo 삭제하기 - DELETE /tasks/{id}

서버 생성 진행하고 PR 보냅니다. 추가 과제는 계속 진행하겠습니다.

2021-01-19 15:49 UTC, hannut91 requested changes
고생하셨어요 ㅎㅎ

2021-01-19 15:49 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/App.java
> +            InetSocketAddress address = new InetSocketAddress(8000);
포트번호를 상수로 분리하는 것은 어떨까요?

2021-01-19 15:49 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/IdGenerator.java
> +    private static Long COUNT = 1L;
자바에서 변하지 않고 상수의 경우에는 지금과 같이 `COUNT`처럼 사용하는데요. 지금은 변하는 값이기 때문에 `count` 소문자로 작성하는게 더 좋을 것 같아요

2021-01-19 15:49 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +        }
`if`가 너무 많아서 이해하기 어려운 것 같아요. 그리고 객체지향 생활체조에서는 들여쓰기를 하나로 제한하고, `else`의 사용도 제한합니다. `if`나 `switch`없이 구현할 수 있을까요?

See also
  - https://developerfarm.wordpress.com/2012/02/03/object_calisthenics_summary/

2021-01-19 15:49 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +                exchange.sendResponseHeaders(200, content.getBytes().length);
단순한 숫자 `200`을 사용하는 대신 `Ok`처럼 상수로 사용하여 표현력을 높이는 건 어떨까요?

2021-01-19 15:49 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/Tasks.java
> +    }
`ArrayList`로 만드는 이유가 있을까요?

2021-01-19 21:47 UTC, etff commented on app/src/main/java/com/codesoom/assignment/IdGenerator.java
> +    private static Long COUNT = 1L;
값이 변하기 때문에 그렇게 하는게 좋을 것같습니다

2021-01-19 21:57 UTC, etff commented on app/src/main/java/com/codesoom/assignment/Tasks.java
> +    }
전체적으로 단순히 자료를 넣고 빼는 용도에서 ArrayList로 만들었습니다.
Map 같은 다른 자료구조가 필요하다고 생각하지 않았습니다.

혹은 질문하신 의도가 get을 할 때 ArrayList로 감싼 이유라면,
리스트의 경우 외부로 내부 참조를 노출 할 수 있기 때문에 

new ArrayList<>(리스트)로 방어 복사를 하거나
Collections.unmodifiableList를 사용하고 있습니다.

2021-01-19 22:06 UTC, etff commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +        }
개발하게 되면 고민하게되는 주제인 것 같습니다.  😀

2021-01-20 17:02 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +            }
body가 비어있지 않으면 보다 body가 있으면 이 더 읽기 좋은 것 같아요.
body가 있으면으로 작성할 수 있을까요?

2021-01-20 17:02 UTC, hannut91 commented on app/src/test/java/com/codesoom/assignment/TaskTest.java
> +    }
테스트도 작성해주셨군요! 좋네요 ㅎㅎ

2021-01-20 17:02 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/Tasks.java
> +    }
그렇군요! 감사합니다 ㅎㅎ

2021-01-21 12:39 UTC, etff commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +            }
빠른 실패를 통해 처리하는게 좋은 방법인 것같습니다.

2021-01-21 12:42 UTC, etff commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +            Optional<Task> foundTask = tasks.findTask(pathVariable);
이 부분은 리뷰어들마다 다양한 의견이 있는 것같습니다.
task, findTask, foundTask 👀

윤석님 회사에서는 정해진 규칙이 있으신가요?

2021-01-21 14:32 UTC, ahastudio commented on app/src/main/java/com/codesoom/assignment/IdGenerator.java
> +}
이 클래스를 전역 함수의 네임스페이스처럼 쓰지 않고 그냥 객체로 쓸 수 있을까요?
(스포를 살짝 하면, Spring은 이런 모든 경우에 평범한 객체를 쓰는 걸 수월하게 도와줍니다.)

2021-01-21 14:32 UTC, ahastudio commented on app/src/main/java/com/codesoom/assignment/JsonConverter.java
> +}
이 클래스도 마찬가지입니다. https://github.com/CodeSoom/spring-week1-assignment-1/pull/5#discussion_r561925183

2021-01-21 14:38 UTC, ahastudio commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +        }
이 다음엔 어떻게 될까요? 이 코드를 읽는 사람은 이 다음에 무슨 일이 벌어질지 모르기 때문에 계속 긴장해서 코드를 읽어야 합니다.
만약 조건문 안에 return이 있었다면 어땠을까요?

2021-01-21 14:49 UTC, etff commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +        }
코드를 다시 살펴보니 return 이 없어 문제가 발생하고 있었네요.
실수 발생을 줄이고 말씀하신 내용도 체크할 수 있었습니다 👍

2021-01-21 15:24 UTC, etff commented on app/src/main/java/com/codesoom/assignment/IdGenerator.java
> +}
new IdGenerator()를 할 수도 있었지만, id는 고유한 값이라 아무곳에서나 new를 사용해 id를 만들면 안될 것같아 static으로 만들었습니다. 
적용사례가 아닌걸까요...?

2021-01-21 15:30 UTC, etff commented on app/src/main/java/com/codesoom/assignment/JsonConverter.java
> +        ObjectMapper objectMapper = new ObjectMapper();
쓰면서도 뭔가 이상했는데 남겨주신 글을 보니 확 와닿네요

2021-01-21 15:32 UTC, etff commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +            }
왜 hasText가 없지 하고 고민을 잠깐했습니다 😂

2021-01-21 15:57 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +            Optional<Task> foundTask = tasks.findTask(pathVariable);
규칙은 정해져있지 않지만 `found`라는 의미를 계속 가지고 가지 않아도 될 것 같아서 저는 안쓰는게 좋을 것 같아요.

2021-01-21 16:02 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +    }
`split`을 사용해서 `/`로 나눈 다음에 마지막 문자열로 id를 추출하는 것 같아요. `substring`이나 정규식을 사용해보는 것도 좋을 것 같아요.

혹은 `마지막`이라는 의미를 더 드러내는 것도 좋을 것 같아요. 이런 메서드가 지원하다면 좋을탠데 아마 없겠죠?
```
path.split("/").last();
```

2021-01-21 16:02 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyServer.java
> +    private InetSocketAddress address;
위에 빈 줄을 추가해서 상수와 변수를 분리해주는 건 어떨까요?

2021-01-21 23:22 UTC, ahastudio commented on app/src/main/java/com/codesoom/assignment/IdGenerator.java
> +}
객체를 반복해서 만들지 않는 게 핵심입니다. https://github.com/CodeSoom/spring-week1-assignment-1/pull/5#discussion_r561928696

2021-01-22 12:53 UTC, etff commented on app/src/main/java/com/codesoom/assignment/MyServer.java
> +    private InetSocketAddress address;
좀더 읽기 좋아질것같네요 👍

2021-01-22 12:54 UTC, etff commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +    }
last()는 없지만 비슷하게 lastIndexOf를 사용해봤습니다

2021-01-22 13:39 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/JsonConverter.java
> +    }
`JsonConverter`가 `Task`만을 위한 것 같아요. 이렇게 매핑하는 것을 task로 옮기면 어떨까 고민을 해봤어요

```java
public class Task {
    static public Optional<Task> fromJson(ObjectMapper mapper, String json) {
        try {
            return Optional.of(mapper.readValue(json, Task.class));
        } catch (JsonProcessingException e) {
            return Optional.empty();
        }
    }
}
```

2021-01-22 14:28 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/JsonConverter.java
> +    }
흠 근데 팩토리 메서드인데 Optional을 돌려준다는 것과 ObjectMapper를 같이 줘야 한다는게 이애하기 어려운 코드가 되었네요 ㅎㅎ 그냥 지금 코드가 더 나은 것 같습니다

2021-01-22 14:33 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/JsonConverter.java
> +    }
다만 extractValue가 task의 title을 돌려준다는 것은 이해하기 어렵네요

2021-01-22 16:38 UTC, etff commented on app/src/main/java/com/codesoom/assignment/JsonConverter.java
> +    }
가져온 task를 사용하려고 했는데 method 이름이 제대로 되지못했네요.
extract title method가 되든가, 다른 방법을 찾아봐야겠네요

2021-01-23 19:05 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +            }
`isEmpty`를 확인했으면 `isPresent`는 확인하지 않아도됩니다 ㅎㅎ

2021-01-23 19:05 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +        }
`body`가 없을 경우에는 빠르게 종료하는 것은 어떨까요?

2021-01-24 07:19 UTC, etff commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +            }
기계적으로 empty present를 사용하니 그런것을 캐치못했네요!!! 감사합니다

2021-01-24 07:20 UTC, etff commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +        }
좋은 방법이라고 생각합니다!

2021-01-24 10:43 UTC, etff commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +        }
enum이나 map으로 해보려고했지만 적용이 쉽지않아
method 분리를 통해서 최대한 if depth 를 줄이는 방향으로 개발했습니다.

2021-01-24 13:57 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ 저희가 기대 이상으로 많이 연습하신 것 같아요. 
처음 작성 했던 코드와 마지막 결과를 비교했을 때 어떤 점이 나아졌는지, 그리고 다음 과제에서는 어떤 것을 더 중점적으로 학습할지 고민해보시면 좋을 것 같습니다.

2021-01-24 13:58 UTC, merged

2021-01-24 14:45 UTC, etff commented
### 과제 후기 

나는야 if factory (?)

과제가 나왔을때 요건이 간단했기때문에 구현하는데 어렵지는 않았습니다.
TEST 파란불을 만들기위해 if문을 많이 사용했습니다. 

짠! 파란불이 나왔는데 결과는 어땠을까요?


코드 리뷰에서 가장 많이 체크받은 곳은 가독성 부분이었습니다.
좀 더 읽기 쉬우려면 어떻게 해야할까요? 트레이너분님께서 많은 질문을 주었습니다.

빠른 실패는 복잡한 유효성 체크를 처리하는데 도움을 줍니다.  개념으로는 아는데 코드로는 안나왔습니다.
왜 안나왔을까...

기계적인 코딩을 했기 때문입니다.
여기는 GET 메서드 => if 존재할 경우, if 존재하지 않을 경우... 여기에 뭔가 또 없으면 if
결과적으로 if가 잔득 붙어 이해하기 어려운 코드가 되었습니다.

윤석님의 리뷰에서 이점을 많이 느겼습니다. 


### static is evil 
너무 강렬하게 기억에 남는 아샬님의 리뷰.
정적 factory로 하나만 두었으면 하는 생각으로 util성 클래스를 만들고는 했습니다.
결과는 static으로 뒤덮힌 클래스가 만들게 되었어요. 이번 계기로 static과 싱글턴에 대해서 충격을 느겼습니다.



### 이번 과제에서 잘 되었던 것 
기간내 TEST 성공, 기능별로 method를 나누기, 역할을 나눠 클래스를 나누기

### 이번 과제에서 잘 안된것 
-의미있는 커밋을 많이 하지 못했습니다. 수정사항 1개 커밋.... 수정사항 1개 커밋...수정사항 1개 커밋
시간에 쫓겨서 그랬다지만 다음에는 의미있는 커밋을 해야겠습니다.

-테스트가 제공(?) 되었지만 스스로 테스트를 많이 만들지 못했습니다. 
다음에는 테스트를 만들고 TDD를 하도록 개발을 해야겠습니다.

I-F문 없애기를 해보려고 했는데 그것을 못한게 아쉽습니다. 
enum이나 map을 이용해서 하는데 simpleFactory에 비해 적용하기가 힘들었습니다.

-눈앞의 내 개발이 밀려있다보니, 다른 트레이너와 다른 개발자분이 개발하는 것들을 살펴보지못한게 아쉽습니다.
또 다른 insight를 얻는 기회를 놓쳤을지도 모르겠네요.