week1 ToDo REST API 만들기
CodeSoom/spring-week1-assignment-1 pull request #6
Opened 2021-01-18 14:34 UTC by yangseungin

아직 테스트코드 미작성과 예외처리가 되지 않았습니다.

2021-01-19 15:38 UTC, hannut91 requested changes
고생하셨어요 ㅎㅎ

2021-01-19 15:38 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/App.java
> +        InetSocketAddress addr = new InetSocketAddress(8000);
포트번호를 상수로 분리하는건 어떨까요?

2021-01-19 15:38 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/App.java
> +        HttpServer httpServer = HttpServer.create(addr, 0);
자명한 경우가 아니면 줄임말은 사용하지 않는게 좋을 것 같아요.  `address`로 사용하는 건 어떨까요?

2021-01-19 15:38 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +    private int idx, code = 200;
`index`를 줄여서 `idx`로 사용하신 것 같아요. `index`로 사용하는게 더 좋을 것 같아요.

`code`는 `statusCode`를 나타내는 것 같아요. 그리고 동시에 2개의 변수를 선언하고 있어서 헷갈려요. 분리해서 선언하는 건 어떨까요?

2021-01-19 15:38 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +        }
if문이 여러번 중첩되어 코드를 따라가기가 힘듭니다. 그리고 중괄호가 생략되어 있어 코드의 어떻게 진행되는지도 파악하기가 힘듭니다. 객체지향 생활체조에서는 들여쓰기를 오직 한 단계를 제한하고 else를 사용하지 말 것을 권장합니다. 조건문을 사용하면 복잡성이 늘어나 코드를 이해하기 어려워지고 유지보수하기 어려워집니다.

See also
  - https://developerfarm.wordpress.com/2012/02/03/object_calisthenics_summary/

2021-01-19 15:38 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +            }
왜 길이가 3인지 이해하기 어려운 것 같아요. `/tasks/3`에서 `/tasks/`만 잘라내는 방법은 어떨까요?

2021-01-19 16:22 UTC, yangseungin commented on app/src/main/java/com/codesoom/assignment/App.java
> +        InetSocketAddress addr = new InetSocketAddress(8000);
상수로 분리하였습니다

2021-01-19 16:24 UTC, yangseungin commented on app/src/main/java/com/codesoom/assignment/App.java
> +        HttpServer httpServer = HttpServer.create(addr, 0);
작성한 코드들을 보니 줄임말을 많이 사용한것 같네요.
수정하였습니다.

2021-01-19 16:31 UTC, yangseungin commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +    private int idx, code = 200;
상태코드마저 코드로 줄여버렸군요... 
변수는 분리하여 선언하였습니다.
수정한 conversation들은 보통 리뷰어분들이 resolve conversation을 해주시나요?

2021-01-19 16:36 UTC, yangseungin commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +            }
/tasks/로 스플릿하여 분리하면되는데 헷갈릴 수 있게 잘랐네요. 수정하였습니다

2021-01-19 16:41 UTC, yangseungin commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +        }
사실 작성하면서도 너무 중첩해서 if문을 사용한 게 아닌가 하여 제일 고민되었던 부분입니다.
적어주신 글을 한번 읽어보고 다시 수정해보겠습니다.

2021-01-20 16:32 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +    }
path에 대해서 내가 처리할 수 있는 것만 처리하고, 처리할 수 없는 경우에는 `NOT_FOUND`를 돌려준다는 의도를 이렇게 드러내보는건 어떨까요? 

```java
String path = exchange.getRequestURI().getPath();
if (path.equals("/") || path.startsWith("/tasks")) {
    sendResponse(exchange, processRequest(exchange));
    return
}

statusCode = HttpStatus.NOT_FOUND;
sendResponse(exchange, "");
```

2021-01-20 16:32 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +    }
`switch`를 사용하실 때는 항상 `default`를 명시해주는게 좋을 것 같아요.
`content`가 변할 수 있는 변수라서 코드를 읽을 때 어떻게 변하는지 계속 추적하면서 읽어서 읽는 사람에게 있어서 어려울 수 있습니다.

```java
switch (exchange.getRequestMethod()) {
    case "GET":
        return processGetRequest(exchange);
    case "POST":
        return processPostRequest(exchange);
    case "PUT":
    case "PATCH":
        return processPutAndPatchRequest(exchange);
    case "DELETE":
        return processDeleteRequest(exchange);
    default:
        return "";
}
```

이렇게 작성하는 것은 어떨까요?

2021-01-20 16:32 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +        if (!hasNumberParameter(path) || !hasIndex(index - 1)) {
`index- 1`이 반복적으로 사용되고 있는데 이건 무엇을 나타내나요? `-1`을 왜 하는지 이해하기 어려운 것 같아요

2021-01-20 16:32 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +        task.setId((long) (tasks.size() + 1));
tasks의 길이로 아이디를 만들어주고 계시군요. 중간에 task가 삭제될 경우 아무런 문제가 없을까요? 예를들어

1
2
3
 
이었는데 2를 삭제하면

1
3

이 되고 여기서 다시 새로운 것을 추가하면

1
3
3

이 될 것 같아요.

2021-01-20 16:36 UTC, yangseungin commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +        }
if문이 여러번 중첩되는 부분들을 어느정도 처리하였고 작은 단위로 메서드를 분리하니 코드의 가독성이 좀더 올라간듯합니다.
모든 else를 제거하였으나 요청메서드를 분기하는 부분에 switch를 사용하였는데 이부분을 어떻게 수정할지 좀 더 생각해보겠습니다.

2021-01-20 16:54 UTC, yangseungin commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +    }
기본을 Not Found로 하고 /와 /tasks인경우만 processRequest메서드를 호출하도록 하려했는데 말씀해주신 방법이 좀더 명확한것 같습니다.

2021-01-20 17:08 UTC, yangseungin commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +    }
저도 switch에서 return할까 고민을 하였는데 메서드의 리턴타입을 또 확인해야되서 저렇게 작성했던것인데 content변수를 추적하며 읽어야한다는 점을 놓친듯합니다.

2021-01-21 10:26 UTC, yangseungin commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +        task.setId((long) (tasks.size() + 1));
아 제가 과제 요구사항을 잘못봤네요
POST의 경우도 /tasks/1 이런식으로 번호가 항상 있는줄 알았습니다

2021-01-21 10:57 UTC, yangseungin commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +        task.setId((long) (tasks.size() + 1));
Task listk를 Map으로 변경해보겠습니다.

2021-01-21 13:25 UTC, yangseungin commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +        if (!hasNumberParameter(path) || !hasIndex(index - 1)) {
arrayList를 사용하였고 index가 0부터시작하고 id값은 1부터시작하여서 작성했던 내용인데 Map으로 수정하여 변경하였습니다.

2021-01-21 13:37 UTC, yangseungin commented
안녕하세요. 현재 TodoHttpHandler에서 모든 작업이 이루어지고있어서 너무 비대해진것 같은데 클래스를 분리하는편이 좋을까요?

2021-01-21 15:48 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +        }
`hasNumberParameter`는 단순히 파라미터가 존재하는지만 확인하는 줄 알았는데 `inputId`를 변경하네요.
정말 파라미터가 있는지만 확인하거나, 값을 받아서 다르게 처리하는게 좋을 것 같아요

2021-01-21 15:48 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +        return false;
`split`대신에 `replace`를 사용하는건 어떨까요?

```java
path.replace("/tasks/", "");
```

2021-01-21 15:48 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +    }
`byId`에서 by는 무엇을 의미하나요?

2021-01-21 15:49 UTC, hannut91 commented
각 path에대해서 처리할 책임을 누가 있는지 생각해보고 그 책임을 나눠보면 좋을 것 같아요 ㅎㅎ

2021-01-22 10:16 UTC, yangseungin commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +        }
hasNumberParameter에서는 파라미터가 존재하는지 체크만하고 값을 넣어주는것을 분리하였습니다.

2021-01-22 10:17 UTC, yangseungin commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +    }
입력받은 아이디값에의해 변경된다는 의미로 사용하였는데 byId보다 inputId가 명확한듯하여 변경하였습니다.

2021-01-22 13:19 UTC, ahastudio commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +    private int statusCode = HttpStatus.OK;
`inputId `, `statusCode`는 마치 전역 변수처럼 쓰이는 것 같습니다.

2021-01-22 13:43 UTC, yangseungin commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +    private int statusCode = HttpStatus.OK;
입력받은값과 상태코드를 전역변수로 사용하였습니다.
상수가아닌 전역변수를 사용하여 호출하는 메소드에 의해 여러군데에서 호출되고있어서 안좋다고 말씀해주신게 맞을까요?

2021-01-22 13:51 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +    }
`jsonToTask`가 string과 id를 둘다 받는게 저는 어색해보입니다. 왜냐하면 두 가지 일을 하고 있기 때문이에요. 여기서는 json으로부터 task를 만드는 일만하고 id를 지정하는 곳은 다른 곳에서 하는게 좋을 것 같습니다

2021-01-22 13:53 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +    }
`Optional`은 값이 있을 수도 있고 없을 수도 있다 라는 컨텍스트로 의도를 명확하게 드러냅니다. 왜 -1인지 이해하기 어려운 것 같아요.

2021-01-22 13:56 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +    private int statusCode = HttpStatus.OK;
전역변수는 값이 어떻게 변할지 몰라 계속해서 추적해야 합니다. 전역변수를 사용하지 않고 문제를 해결할 수 있을까요?

2021-01-22 18:42 UTC, yangseungin commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +    private int statusCode = HttpStatus.OK;
inputId는 필요한 메서드에서만 사용하도록 지역변수로 분리하였고 statusCode는 응답자체를 Response클래스로 분리하여 사용하도록 하였습니다.

2021-01-22 18:43 UTC, yangseungin commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +        return false;
수정하였습니다.

2021-01-22 19:20 UTC, yangseungin commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +    }
수정을 하였으나 Optional 사용에 익숙하지 않아서 좀더 학습이 필요할듯합니다.

2021-01-22 19:38 UTC, yangseungin commented on app/src/main/java/com/codesoom/assignment/TodoHttpHandler.java
> +    }
따로 id값을 받아서 task에 set을 할 필요가 없어보여서 제거하였습니다

2021-01-23 18:55 UTC, hannut91 approved these changes
테스트가 올바르게 동작하지 않은 것을 찾아서 문제를 해결하신 것이 인상깊습니다 ㅎㅎ
문제를 아주 잘 해결해주셨네요 ㅎㅎ  그런데 지금은 자바라는 훌륭한 도구를 아직 완벽하게 사용하진 않은 것 같아요. 자바는 객체지향 프로그래밍으로 사용할 때 가장 좋은 도구로서 활용될 수 있는데 지금은 단순히 언어만 자바인 것 같아요. 시스템의 기능에 대해서 책임과 역할로 객체를 분류하고 협력을 통해서 프로그램을 만들어야 하는데 지금은 동일하게 자바스크립트나 다른 언어를 사용해도 동일한 결과를 얻을 수 있을 것 같아요.

예를들어 `path`에 대해서 지금은 `extractNumber`라는 함수를 사용해서 얻고 있는데, 절차적인 방식으로 문제가 해결되고 있는 것 같아요. 그래서 계속해서 계산에 필요한 데이터를 외부에서 넘겨주고 있어요. 객체지향 프로그래밍에서는 객체의 행동과 상태가 모두 객체가 가지고 있고, 우리가 필요한 행위에 대해서 객체가 자율적으로 행동할 수 있어야 해요. 예를들어서 다음과 같이 할 수 있을거에요.

```Java
Path path = new Path(exchange.getRequestURI().getPath());
String parameter = path.pathParams("/tasks/");
Long id = Long.parseLong(parameter);
```

이번 강의에서도 그랬고, 앞으로도 객체지향에 대해서 깊게 다루지는 않지만 도움이 되실까봐 남겨봐요 ㅎㅎ

2021-01-23 18:56 UTC, hannut91 commented
이번 과제를 통해서 무엇을 배우셨나요?

2021-01-24 10:20 UTC, yangseungin commented
코멘트를 작성하고 있었는데 작성하다보니 회고가 되어버려 회고로 작성하였습니다.
https://giantdwarf.tistory.com/50
https://github.com/CodeSoom/spring-week1-assignment-1/pull/6#pullrequestreview-574868424 조언 감사합니다. 과제를 하면서도 절차지향적인 코드를 작성한거같아 고민이 많았습니다. 

https://github.com/CodeSoom/spring-week1-assignment-1/pull/6#issue-556850769 처음에 언급한 테스트코드를 끝까지 작성하지 못하였고 아쉬운점이 많이 남았지만 부족한점들이 무엇인지 알 수 있었던 과제였습니다.

2021-01-24 14:03 UTC, merged