Rlawlstjd0077
CodeSoom/spring-week1-assignment-1 pull request #7
Opened 2021-01-18 14:43 UTC by rlawlstjd0077

진행 내역 
- GET /tasks
- GET /tasks/{id}
- POST /tasks

질문
- Task의 id 값을 생성해주는 규칙이 어떻게 되는지 궁금합니다.
- 패키지 분리를 어떻게 해야 할지가 생각보다 많이 고민이 되더라구요 .. 참고 해볼만한 자료가 혹시 있을까요 ..? 있으시면 추천 부탁드립니다!

느낀점
- 테스트 코드의 강제성이 얼마나 중요한지가 느껴졌습니다.. 나름대로 러프하게 구현을 해놓고 점진적으로 발전시켜나가보자 ..! 라는 생각을 했는데 막상 해보니 오만한 생각이었음을 느낍니다. 구현을 하다 보니 목표했던 범위가 너무 컸었고, 명확한 체크 포인트가 없다보니 앞으로 뭘 구현해야 하고 현재는 어디까지 구현이 되었는지 파악이 안되는 상황이 펼쳐지더라구요 .. 
- 그래서 구현하고자 하는 목표를 생각할 때 그 단위를 명확히 하고 최대한 단순하게 구성을 해야 겠다는 생각이 들었습니다.

2021-01-19 05:34 UTC, rlawlstjd0077 commented
### 2020-01-19
진행 내역
- PUT/PATCH /tasks/{id}
- DELETE /tasks/{id}
(진행 내역을 어떤 단위로 적어야 할지.. 고민이 되네요)

질문
- test script를 한번 돌려봤었는데 어느 부분에서 test case가 실패 했는지 확인해볼 수 있는 방법이 있을까요? 

느낀점
- 최대한 작게작게 나눠서 구현을 해보자는 생각으로 구현을 했지만 지금껏 해왔던 버릇 (구현, 문제 해결에 급급한)이 굳어져 있어서 아직은 낯선감이 있는 것 같습니다.. 일정 탓이었다고 둘러대고 싶지만 (ㅠ) 결국에는 품질과 연관이 되어 있는 부분이기에 힘들더라도 고쳐나가야 되겠다고 다짐했습니다.
- 여러 예외 상황에 대한 처리 분기를 어떻게 구성을 해야 할지가 고민이 많이 되는 것 같습니다. 예외 처리는 늘 쉽지 않군요 ㅠ
- 코드를 작성하는 경우 큰 부분(좀 더 추상적인 부분)을 먼저 구현하고 그 다음 작은 부분들을 구현하는 계층적인 순서로 구현을 하고 싶었지만 늘 작은 부분에 막혀 씨름하고 있는 경우가 많은 것 같습니다.. 

추후 계획
- Test Case 통과

2021-01-19 15:15 UTC, hannut91 requested changes
고생하셨어요 ㅎㅎ

2021-01-19 15:15 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/App.java
> +    private static final int port = 8000;
자바에서는 변하지 않는 상수의 경우에는 `PORT` 이렇게 작성합니다

2021-01-19 15:15 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/App.java
> +        HttpHandler handler = new MyHandler(taskService);
의존성 주입을 하셨군요 ㅎㅎ좋네요

2021-01-19 15:15 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/models/Task.java
> +                '}';
```Java
return String.format("Task { id=%s, title=%s }", id, title);
```

이렇게 작성하는 것은 어떨까요?

2021-01-19 15:15 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/service/TaskService.java
> +    }
`tasks`에서 만약 값이 존재하지 않을 경우 예외를 발생시키려고 하신 것 같아요. 이러면 사용하는 곳에서 내가 다르게 처리하고 싶을 때는 어려워질거에요. 

반환값이 `Optional<Task>`이고 반환받은 곳에서 만약 없을 경우를 처리하는게 더 좋을 것 같아요

2021-01-19 15:15 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/util/JsonUtil.java
> +}
![image](https://user-images.githubusercontent.com/14071105/105052543-5a908a80-5ab3-11eb-8d30-51231d7231c3.png)

```suggestion
}

// 새로운 코드
```

코드 마지막 줄에는 빈 줄이 하나가 추가되어야 합니다. 그렇지 않으면 위와 같이 GitHub에서 표시가 됩니다.

빈 줄을 추가해야하는 이유는 GitHub의 컨벤션 때문에 그렇습니다. GitHub은 변경사항을 표시할 때 변경전 부분과 변경 후 를 모두 보여줍니다. 

```
console.log('Hello');
```

만약 위와 같이 빈 줄이 없는 코드에서 아래에 코드를 추가하게 되면 Git은 다음과 같이 표시합니다.

```
- console.log('Hello');
+ console.log('Hello');
+ console.log('world!');
```
저는 단순히 아래 한 줄만 추가했는데 왜 세줄이 변경되었다고 나오는 걸까요? 그 이유는 줄바꿈 문자 `\n`가 들어갔기 때문입니다. 

```
- console.log('Hello');
+ console.log('Hello');\n
+ console.log('world');
```
만약 미리 빈 줄을 하나 추가한 상태에서 아래에 새로운 코드를 작성할 경우에는 다음과 같이 보여집니다.

```
+ console.log('world');
```
이미 \n이 추가되어 있기 때문이죠. 따라서 코드 마지막 줄에 빈 줄 하나를 항상 추가해주는게 좋습니다.

2021-01-19 15:15 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/web/MyHandler.java
> +                    sendResponse("Method Not Allowed", 405, exchange);
상태코드를 숫자를 사용하는 대신 상수를 사용하면 더 좋을 것 같아요. 예를들면 200 같은 상태코드도 `Ok`처럼 사용할 수 있는 것처럼욧

2021-01-20 06:59 UTC, rlawlstjd0077 reviewed
이 부분은 어제 남겨둔 Comment 들이었는데 .. Submit을 하지 않아서 (?) 보여지지가 않았던 것 같습니다.
이왕 이야기가 나온 김에 구체적인 코드레벨에 질문의 경우에 아래 처럼 Line에 다가 Comment를 달아서 질문을 해보면 어떨까 해서 남겨 보았습니다.
이런 방법도 괜찮을까요? 괜찮다고 하시면 추후 적극 활용 하겠습니다 .. ㅎㅎ

2021-01-20 06:59 UTC, rlawlstjd0077 commented on app/src/main/java/com/codesoom/assignment/App.java
> +    private static final int port = 8000;
네 맞습니다 .. 놓친 부분이네요 ㅠ 피드백 감사합니다 :)

2021-01-20 07:03 UTC, rlawlstjd0077 commented on app/src/main/java/com/codesoom/assignment/models/Task.java
> +                '}';
가독성 측면에서 봤을 때 추천해주신 방법이 더 좋을 것 같네요. 동의합니다 !

2021-01-20 07:05 UTC, rlawlstjd0077 commented on app/src/main/java/com/codesoom/assignment/service/TaskService.java
> +    }
혼자서 구현 당시에는 생각치 못한 부분이네요 .. ㅠ 정말 감사합니다 !
변할 여지가 있는 분기라면 throws 를 해주지 않도록 머릿속에 넣어갑니다 :)

2021-01-20 07:37 UTC, rlawlstjd0077 commented on app/src/main/java/com/codesoom/assignment/util/JsonUtil.java
> +}
그렇군요 ... 흥미롭네요 ! 감사합니다 :)

2021-01-20 07:46 UTC, rlawlstjd0077 commented on app/src/main/java/com/codesoom/assignment/web/MyHandler.java
> +                    sendResponse("Method Not Allowed", 405, exchange);
이부분은 동의합니다! 다만 생각했을 때 두가지 방법이 있을 것 같다는 생각이 들었습니다.
- Enum 으로 상태 코드 정의
- 별도 정적 클래스에 상수들을 정의
어떤 방법이 더 괜찮을까요?? 어떻게 생각하시는지 궁금합니다!

2021-01-20 07:49 UTC, rlawlstjd0077 commented on app/src/main/java/com/codesoom/assignment/App.java
> +        HttpHandler handler = new MyHandler(taskService);
감사합니다 :) 뿌듯하네요 ...

2021-01-20 08:43 UTC, rlawlstjd0077 commented
> 벌써 부터 회고가 좋습니다 ㅎㅎ
> 
> > 패키지 분리를 어떻게 해야 할지가 생각보다 많이 고민이 되더라구요 .. 참고 해볼만한 자료가 혹시 있을까요 ..? 있으시면 추천 부탁드립니다!
> 
> 패키지는 관심사에 따라 분리하는게 좋을 것 같아요 ㅎㅎ 이 부분은 강의를 진행하면서 더 배우실 수 있습니다. 참고 해볼만한 자료가 사실 Domain Driven Development인데 너무 어려워서....
> 
> > test script를 한번 돌려봤었는데 어느 부분에서 test case가 실패 했는지 확인해볼 수 있는 방법이 있을까요?
> 
> 터미널에서 테스트 결과를 확인하실 수 있습니다. ㅎㅎ 지금 테스트에 작성된 포트번호와 달라서 안되는 것 같네요

2021-01-20 11:57 UTC, rlawlstjd0077 commented
## 2021-01-20
### 진행 내역
- 'TaskService' 테스트 코드 추가
- Task 검색 실패시 예외 처리 분기 수정
- Test Case 통과 

### 느낀점
- 동기분들의 PR도 함께 보고 있는데 생각보다 그 과정에서 미쳐 생각하지 못한 부분도 깨닫고 배울점들도 너무 많았습니다. 앞으로도 적극 활용하여 많은 부분을 배우고 싶습니다.
- 비즈니스 로직에 대한 테스트 코드를 작성해보면서 TDD에서 주워들은 'Negative Case 부터 작성해라'는 조언을 적용 해보았는데 기대 이상으로 편안함을 선사해주는 것 같습니다.. 습관화가 절실하다는 것을 느낍니다..

2021-01-20 12:01 UTC, rlawlstjd0077 commented on app/src/main/java/com/codesoom/assignment/service/TaskService.java
> +        return findTaskById(id).orElseThrow(() -> new IllegalArgumentException("Failed to find task (ID: " + id + ")"));
task를 찾지 못한 경우 'IllegalArgumentException' 을 던지게 하였는데 이 부분에 대해서는 따로 커스텀 예외 클래스를 만들어야 좋을지 아니면 제공되는 예외 클래스를 이용하면 좋을지 고민이 되네요.. 트레이너님은 어떻게 생각하시는지 궁금합니다 !

2021-01-20 15:27 UTC, hannut91 commented
Negative Case부터가 아니라 Happy case부터 작성하는 것이 좋다고 생각하는데, Negative Case부터 작성하면 무엇이 좋은가요?

2021-01-20 15:40 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/service/TaskService.java
> +        return findTaskById(id).orElseThrow(() -> new IllegalArgumentException("Failed to find task (ID: " + id + ")"));
커스텀 에러를 주는게 좋을 것 같은데, 지금은 단순하니 괜찮은 것 같아요 ㅎㅎ

2021-01-20 15:40 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/util/JsonUtil.java
> +}
기계인간님의 블로그 글을 참조하시면 좋을 것 같아요

https://johngrib.github.io/wiki/intellij/#%ED%8C%8C%EC%9D%BC-%EB%A7%88%EC%A7%80%EB%A7%89%EC%97%90-%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C-1%EA%B0%9C%EC%9D%98-%EA%B0%9C%ED%96%89-%EB%AC%B8%EC%9E%90-%EC%B6%94%EA%B0%80%ED%95%98%EA%B8%B0

2021-01-20 15:40 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/web/MyHandler.java
> +    private void processRequest(RequestInfo requestInfo, HttpExchange exchange) throws IOException {
Switch문 없이 Map을 사용해서 구현할 수 있을까요?

2021-01-20 15:40 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/web/MyHandler.java
> +        }
path가 올바른지 별도의 함수로 확인하고 있는데, `requsetInfo`가 스스로 확인할 수 있도록 수정해보는 것은 어떨까요?

`requestInfo.isValidPath()`

2021-01-20 15:40 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/web/MyHandler.java
> +            sendResponse(responseJson, 200, exchange);
간단하게 상수로 만들어주는게 좋을 것 같아요 ㅎㅎ

2021-01-20 15:40 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/web/MyHandler.java
> +    private long parseIdFromPath(String path) throws NumberFormatException {
너무 방법이 많아서 ㅎㅎ 여러가지 해결방법을 풀어보고 

어떻게 더 효과적으로 해결할 수 있을까?
어떻게 더 효율적으로 해결할 수 있을까?

를 고민하시면 좋을 것 같아요. 지금 완벽한 해결책을 찾을 순 없어요. 더 중요한 것은 지속적으로 개선하는 것이에요.
만약에 이와 비슷한 문제를 만났을 때, 그 다음번에는 더 개선한 버전을 만들어보세요

2021-01-21 04:42 UTC, rlawlstjd0077 commented on app/src/main/java/com/codesoom/assignment/util/JsonUtil.java
> +}
감사합니다 :)

2021-01-21 04:43 UTC, rlawlstjd0077 commented on app/src/main/java/com/codesoom/assignment/web/MyHandler.java
> +    private long parseIdFromPath(String path) throws NumberFormatException {
그게 맞는 것 같습니다 :) 돌아보니 너무 막연하게 해결책을 묻고 있었네요 .. ㅎㅎㅎ 부끄럽습니다.

2021-01-21 04:45 UTC, rlawlstjd0077 commented on app/src/main/java/com/codesoom/assignment/web/MyHandler.java
> +    private void processRequest(RequestInfo requestInfo, HttpExchange exchange) throws IOException {
Map을 활용한 방법도 있을 것 같네요! 다른 방법도 고려해보고 시도를 해봐야 겠습니다. 감사해요 :)

2021-01-21 04:48 UTC, rlawlstjd0077 commented on app/src/main/java/com/codesoom/assignment/web/MyHandler.java
> +        }
생각해보니 path validation의 책임은 Handler가 아니라 RequestInfo 클래스에 더 가까운 것 같습니다.
이런식으로 최대한 책임을 분리해서 클래스를 날씬 하게 만들어야 겠다는 힌트를 얻어갑니다 :)

2021-01-21 10:52 UTC, rlawlstjd0077 commented
> Negative Case부터가 아니라 Happy case부터 작성하는 것이 좋다고 생각하는데, Negative Case부터 작성하면 무엇이 좋은가요?
어디서 본가 했더니 토비의 스프링 2장 테스트 에서 봤던 내용이더라구요 ㅎㅎ 
(토비의 스프링 내용중 .. )"...개발자는 빨리 테스트를 성공하는 것을 보고 다음 기능으로 나아가고 싶어하기 때문에 긍정적인 경우를 골라서 테스트를 먼저 작성하게 되기 쉽다. 그래서 테스트를 작성 할 때 부정적인 케이스를 먼저 만드는 습관을 들이는 게 좋다 .. 이를 통해 예외 적인 상황을 빠뜨리지 않는 꼼꼼한 개발이 가능하게 된다."

2021-01-21 13:00 UTC, rlawlstjd0077 commented
## 2021-01-21
### 진행 내역
- Handler 에서 처리(switch 분기로)하던 로직을 'HttpRequestContext' 클래스로 분리 
- HTTP Method 별 로직을 Controller 클래스로 각각 분리하여 전략 패턴(?) 으로 처리
- HTTP Request 관련 Magic Number 등 상수, Enum 으로 분리
### 느낀점
- 이번 작업에서는 각 클래스의 책임이 무엇인지 책임을 어떻게 분리할 것인지를 중점적으로 고민을 했었습니다. 클래스에 대해서 '최소한의 책임을 지게 하자' 라고 생각하니 막연하던 것이 조금은 감이 잡혀가는 것 같습니다. 
- 진행을 하다보면 자꾸 답을 찾으려고 하는 것 같습니다. 오늘도 어제보다는 '조금 더 나은 쓰레기'(?)를 만들어가자는 생각을 가지려고 노력해봅니다 ..

2021-01-21 13:18 UTC, rlawlstjd0077 commented on app/src/main/java/com/codesoom/assignment/service/TaskService.java
> +    private IdGenerator idGenerator = new IdGenerator();
기존에 ID를 생성하는 로직이 TaskService의 책임은 아닌 것 같아서 분리하기로 결정했습니다.

2021-01-21 13:18 UTC, rlawlstjd0077 commented on app/src/main/java/com/codesoom/assignment/service/TaskService.java
> +    private Task getTaskByIdOrThrow(long id) {
이 부분은 중복을 줄이기 위해서 메소드 분리를 하였는데 아래 find 메소드와는 의미의 차이을 두고 싶어서 'get' 접두어를 사용했고 'Exception' 을 던진다는 정보를 포함시켰습니다. 이 네이밍은 어떻게 생각하시나요 ?!

2021-01-21 14:13 UTC, hannut91 commented
그렇군요 ㅎㅎ 근데 저는 항상 Happy case부터 먼저 작성합니다. 왜냐하면 예외를 생각하다보면 너무 복잡해져서 압도당하기 때문이에요.
먼저 내가 원하는 기능이 올바르게 동작할 경우를 작성하고, 혹시 이런 경우에는 어떻게 되지? 같은 스펙들을 추가해가면서 만듭니다

2021-01-21 14:26 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/service/TaskService.java
> +    private Task getTaskByIdOrThrow(long id) {
음 저라면 반환하는 Type을 Optional을 사용해서 의도를 드러낼 것 같아요. 그러면 이 메서드가 실패할 수 있다는 것을 명확하게 의도를 드러낼 수 있고, 실패할 경우 어떻게 할지 선택할 수 있기 때문이에요

2021-01-22 04:25 UTC, rlawlstjd0077 commented on app/src/main/java/com/codesoom/assignment/util/JsonUtil.java
> +}
적용했습니다 !! 자료 공유 감사합니다 :)

2021-01-22 04:25 UTC, rlawlstjd0077 commented on app/src/main/java/com/codesoom/assignment/util/JsonUtil.java
> +}
적용했습니다. 자료 공유 감사해요 :)

2021-01-22 04:26 UTC, rlawlstjd0077 commented on app/src/main/java/com/codesoom/assignment/service/IdGenerator.java
> +    private int idCnt;
'객체지향 생활체조' 에서 본 내용이네요 .. 맞습니다.

2021-01-22 12:15 UTC, rlawlstjd0077 commented on app/src/main/java/com/codesoom/assignment/App.java
> +        strategyProcessMap.put(HttpRequestMethod.DELETE, new DeleteRequestController());
네이밍에 미스가 있었던 것 같습니다 .. ㅎㅎ 동일한 의미로 `requestControllerMap` 이 맞을 것 같네요

2021-01-22 12:18 UTC, rlawlstjd0077 commented
# 2021-01-21
## 진행 내역
- 추가 도메인 처리를 위한 HttpRequestContext, RequestController 리팩토링
- 도메인 추가 (User)에 따른 연관 클래스, 테스트 코드 추가
- 패키지 구조 변경 (1차적으로 Layer 분리 2차적으로 Domain 분리를 했지만 web layer 쪽이 맘에 들지 않음 .. )

2021-01-22 13:02 UTC, rlawlstjd0077 commented on app/src/main/java/com/codesoom/assignment/web/HttpRequestContextBase.java
> +        }
사실 이 부분에 대해 고민이 많은데 .. 현재는 이렇게 Base 메서드에서 상에서 일괄적으로 Controller 처리 중에 발생하는 예외를 처리해주고 있습니다.
개선 방법으로 생각을 했던 것이 예외 처리를 없애고 Controller 에서 각자 예외를 처리하여 reponse 객체를 반환해주면 어떨까 생각했는데 어떻게 생각하시나요 ?>!

2021-01-22 13:02 UTC, rlawlstjd0077 commented on tests/__tests__/api.spec.js
> +
음 .. Domain을 추가하면서 Test Script도 추가를 했는데 같이 올렸네요 .. 이 부분은 롤백하는게 좋을까요 ?

2021-01-22 13:16 UTC, ahastudio commented on app/src/main/java/com/codesoom/assignment/App.java
> +        handler.addRequestContext(TaskHttpRequestContext.BASE_PATH, taskRequestContext);
두 가지 질문을 던져보면 좋을 것 같습니다.

1. 만약 `TaskHttpRequestContext` 인스턴스 둘을 만들고 이들을 각각 다른 경로로 배치하고 싶다면 어떻게 해야 할까요?
1. `TaskHttpRequestContext` 객체는 `BASE_PATH`를 알아야 할까요? 반대로, `main`은 다른 클래스의 내부를 참고해서라도 `BASE_PATH`를 알아야 할까요?

2021-01-22 14:02 UTC, rlawlstjd0077 commented on app/src/main/java/com/codesoom/assignment/App.java
> +        handler.addRequestContext(TaskHttpRequestContext.BASE_PATH, taskRequestContext);
피드백 감사합니다 :) 

> 1. 만약 `TaskHttpRequestContext` 인스턴스 둘을 만들고 이들을 각각 다른 경로로 배치하고 싶다면 어떻게 해야 할까요?

현재는 달리 방법이 없을 것 같습니다. `BASE_PATH` 를 고정 시킴으로 인해서의 문제인데 생각해보면 `BASE_PATH` 고정 시킬 이유는 없는 것 같습니다.
> 2. `TaskHttpRequestContext` 객체는 `BASE_PATH`를 알아야 할까요? 반대로, `main`은 다른 클래스의 내부를 참고해서라도 `BASE_PATH`를 알아야 할까요?

`BASE_PATH` 를 알아야할 필요는 없습니다. 생각해보면 `TaskHttpRequestContext` path와는 상관없이 동작해야 되기 때문에 path를 외부에서 주입 받게 수정하고 main에서 path를 주입해주도록 하면 좋을 것 같습니다

2021-01-22 14:09 UTC, hannut91 commented on tests/__tests__/api.spec.js
> +
아니에요 ㅎㅎ 괜찮습니다

2021-01-22 14:10 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/web/HttpRequestContextBase.java
> +        }
각각의 장단점을 고려해보면 좋을 것 같아요 ㅎㅎ 정답이 없는 것이라서 무엇이 더 나은가 판별하는게 더 좋아보입니다. ㅎㅎ

2021-01-22 14:12 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/web/HttpRequestContextBase.java
> +        }
여기서 처리해준다면 각 컨트롤러에서 에러를 던지기만하고 여기서 각 에러에 대해서 응답을 어떻게 줄 건지만 결정할 수 있어서 전 괜찮은 것 같아요

2021-01-23 11:37 UTC, rlawlstjd0077 commented on app/src/main/java/com/codesoom/assignment/web/HttpRequestContextBase.java
> +        }
생각해본 방법으로 시도를 해보았는데 만약 그렇게 할 경우 컨트롤러에서 일일이 예외처리를 해주어야 할텐데 그렇게 되면 제 생각에는 쓸데 없는 예외처리 로직이 될 것 같다고 생각이 들더라구요. 
그리고 현재 예외처리 레벨이 정상응답 처리 로직과 동일한 레벨에 있어서 이해하기도 더 수월 할 것 같다고 생각했습니다. (물론 더 명확한 의미의 예외 클래스를 정의하면 더 좋겠지만 .. ㅎㅎ)

2021-01-23 11:41 UTC, rlawlstjd0077 commented
## 2021-01-23
### 진행내역
HttpRequestContext 관련 클래스 리펙토링
- Concrete 클래스의 basePath를 외부에서 주입 받도록 수정
- 도메인별 HttpRequestContext 분리 (collection, item 각각 별도의 클래스로 분리)

2021-01-23 18:42 UTC, hannut91 approved these changes
테스트도 직접 작성하시고 중복을 제거하려고 하고 예외를 어떻게 효과적으로 처리할 수 있을지 고민한 흔적이 많이 보입니다 ㅎㅎ 과제의 의도는 간단한 REST API를 만드는 것이었는데, 어떻게 잘 만들 수 있을까 많이 연습을 하신 것 같아요.

스프링으로 하면 내가 고민했던 부분이 어떻게 말끔하게 처리되는지 비교해보시면 좋을 것 같아요

2021-01-23 18:42 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/web/HttpRequestContextBase.java
> +        }
스프링을 사용하면 아주 깔끔하게 되기 때문에 크게 걱정은 없지만 좋은 고민이었던 것 같아요 ㅎㅎ

2021-01-24 13:16 UTC, rlawlstjd0077 commented
많은 것을 배웠지만 .. 가장 크게는 아래 3가지를 배운 것 같습니다.

### 책임 분리
- 계속해서 더 나은 구조를 고민하다 보니 한가지 확실하게 얻는 것이 '이 클래스가 이 코드를 알아야 할까?/책임이 있을까?' 라는 생각을 제일 많이 하게 된 것 같습니다. 
- 그러니 자연스럽게 좋은 구조가 만들어지면서 중복이 제거되고 확장성이 좋아지는 결과를 얻을 수 있었던 것 같습니다.  
### 예외 처리 
- 이전까지는 예외 처리를 무책임 하게 던져 버리거나 무의미 하게 catch 블록으로 묶어주곤 했는데 과제를 진행하면서 처리 전략에 대해서  학습도 해보고 어떻게 구조를 잡을지에 대해서도 많은 고민을 해볼 수 있었습니다.
- 그렇다고 완벽하게 터특한 것은 아니지만 .. 로직을 설계 하고 구현할 때 예외처리를 어떤 방식으로 처리를 해줘야 할지는 옵션을 알게 된 것 같습니다.
### NPE와 맞서 싸우는 방법
- Optional 클래스를 이전에는 잘 사용하지도 않았고 왜 써야 하는지도 잘 모르는 상태에서 이번에 제대로 학습을 해보았습니다. 
- 결론적으로는 코드를 읽는 사람, API를 쓰는 사람 으로 하여금 명확한 의도를 표현하는 것 이라는 것을 깨닫게 되었습니다.

2021-01-24 14:06 UTC, merged

2021-01-24 14:07 UTC, hannut91 commented
고생하셨습니다 ㅎㅎ 다음 과제에서는 어떤걸 중점적으로 학습할지 고민해보면 좋을 것 같아요!