Initial commit
CodeSoom/spring-week1-assignment-1 pull request #8
Opened 2021-01-18 16:18 UTC by dongwooklee96

- 과제를 수행하기 전에, 수업 시간에 작성했던 소스를 따라서 작성해보았습니다.

2021-01-19 14:50 UTC, hannut91 requested changes
고생하셨습니다 ㅎㅎ

2021-01-19 14:50 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/App.java
> +            InetSocketAddress address = new InetSocketAddress(8001);
코드에서 Magic literal을 사용하고 있습니다. Magic literal이란 코드에서 단순한 숫자 혹은 문자열을 직접사용하는 것을 말합니다. 

예를들어서 수강 신청한 학생들이 있는데 신청한 학생들을 선착순 3명까지 자르기로 했습니다.

```js
const applicants = ['윤석', '수형', '기현', '기환', '아샬'];

// 강의를 들을 수 있는 최대 인원은 3명입니다.
const students = applicants.slice(0, 3);

console.log(students); // [ '윤석', '수형', '기현' ]
```

그래서 3명의 학생들이 걸러졌습니다. 하지만 코드만 보면 왜 3명이지? 4명이나 5명은 안되는지 알 수 없습니다. 주석을 달아서 설명했습니다. 딱히 문제는 없어보입니다. 하지만 만약 강의 정원을 늘리던지, 줄이면 주석도 수정해야하고 코드도 수정해야합니다. 

중복이 발생한 겁니다. 최악의 경우는 주석과 코드가 다를 경우 입니다. 테스트코드가 없다면 주석이 맞는건지 코드가 맞는건지 아무도 판별할 수 없습니다. 

그렇다면 주석없이 같은 표현을 하려면 어떻게 해야할까요?

```js
const LECUTRE_LIMIT = 3;

const applicants = ['윤석', '수형', '기현', '기환', '아샬'];

const students = applicants.slice(0, LECUTRE_LIMIT);

console.log(students); // [ '윤석', '수형', '기현' ]
```

Magic literal을 표현하는 상수를 만들면 됩니다. 이러면 주석이 없어도 왜 3명인지, 지원자들을 자를 때 무엇을 기준으로 자르는지 의도가 바로 드러납니다.

그렇다고 해서 모든 텍스트를 상수로 분리해야 하는 것은 아닙니다. 때로는 그냥 텍스트를 보여주는 것이 오히려 더 이해가 쉬울 수 있어요.

See also
  - https://refactoring.com/catalog/replaceMagicLiteral.html

2021-01-19 14:50 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        }
이부분이 상당히 복잡해보입니다. 점점 다른 메서드들을 추가할 때마다 계속해서 늘어날꺼에요. 어떻게 단순화 할 수 있을까요?

2021-01-19 14:50 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +            this.statusCode = 200;
`200`대신 `Ok`같은 상수를 사용할 수 있을까요?

2021-01-19 14:50 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/models/Task.java
> +        return sb.toString();
StringBuilder는 문자열을 계속해서 더해가는데, 한 번에 뭔가 출력할 수 있는 방법은 없을까요?

다음과 같이 하는 것을 어떨까요?

```Java
return String.format('Task id=%s, title=%s", id, title');
```

2021-01-19 23:58 UTC, dongwooklee96 commented on app/src/main/java/com/codesoom/assignment/App.java
> +            InetSocketAddress address = new InetSocketAddress(8001);
아하 그렇군요 단순히 숫자를 사용하는 것 보다는 상수로 만드는게 더 명확하고 유지보수 하기 좋을 것 같습니다. 
일단 상수로 관리를 하다가 더 나아가서 설정 정보를 자바에서는 어떻게 관리하는지 조사해보고 .properties 파일에서 설정 정보를 관리하는 것 까지 해봐야겠어요

2021-01-19 23:59 UTC, dongwooklee96 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        }
이 부분을 따로 컨트롤러 같은 패키지에서 처리하면 좋을 것 같은 생각이 듭니다.
하지만 uri 분리하는 로직을 구현하지 못해서 우선 그것부터 구현을 한 다음에 분리 해볼 생각이에요 ㅎㅎ

2021-01-20 00:01 UTC, dongwooklee96 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +            this.statusCode = 200;
이 부분 역시 앞의 내용과 비슷한 내용이네요 혹시 상태 코드도 나아가서 .properties를 통해서 관리하는 것을 어떻게 생각하시나요?

2021-01-20 00:02 UTC, dongwooklee96 commented on app/src/main/java/com/codesoom/assignment/models/Task.java
> +        return sb.toString();
확실히 가독성 측면에서 멘토님이 제안하신 부분이 옳은 것 같습니다. 보통 자바에서는 보통 문자열을 사용할 때 String.format()을 사용하는 것이 베스트 프렉티스인지요? 궁금합니다 ㅎㅎ

2021-01-20 14:18 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/models/Task.java
> +        return sb.toString();
사실 저는 Template literal이 가장 좋다고 생각해요 ㅎㅎ 근데 자바에서는 지원하지 않기 때문에 그나마 제일 괜찮은 것 같습니다. 베스트 프렉티스인지는 저도 잘 모르겠어요.

Kotlin에서는 그냥 다음과 같이 사용할 수 있어서 더 좋은 것 같아요
```kotlin
"Task id=${id}, title=${title}"
```

2021-01-20 14:19 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +            this.statusCode = 200;
저도 속성으로 관리를 하면 더 좋을 것 같아요 ㅎㅎ 근데 지금은 일단 간단하게 상수로 분리하는 것만으로도 이전보다 더 좋은 것 같아요.

2021-01-20 14:58 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        } else {
if문이 여러번 중첩되어 코드를 따라가기가 힘듭니다. 그리고 중괄호가 생략되어 있어 코드의 어떻게 진행되는지도 파악하기가 힘듭니다. 객체지향 생활체조에서는 들여쓰기를 오직 한 단계를 제한하고 else를 사용하지 말 것을 권장합니다. 조건문을 사용하면 복잡성이 늘어나 코드를 이해하기 어려워지고 유지보수하기 어려워집니다.

See also
  - https://developerfarm.wordpress.com/2012/02/03/object_calisthenics_summary/
  - https://developerfarm.wordpress.com/2012/01/27/object_calisthenics_3/

2021-01-20 14:58 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        }
`id` path parameter를 얻기 위해서 `/`로 구분하여 마지막 문자열을 찾는 것 같아요.
정규식을 사용하거나 혹은 문자열에서 앞에것만 잘라내는 것은 어떨까요? 예를들어 "/tasks/100" 에러 `/tasks/`만 잘라내면 100을 얻을 수 있을 것 같아요

2021-01-20 14:58 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +                this.statusCode = 200;
Magic literal을 사용하는 대신 상수를 정의해서 사용하는 것은 어떨까요?

See also
  - https://refactoring.com/catalog/replaceMagicLiteral.html
  - https://tools.ietf.org/html/rfc2616#section-10

2021-01-20 14:58 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +                }
`requestBody가 비어있지 않으면` 보다 `requestBody가 있으면` 이 더 읽기 좋은 것 같아요. 부정문은 한 번 더 생각해야되서 대부분의 경우 긍정문을 사용하는게 좋습니다

2021-01-20 14:58 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +                this.statusCode = 200;
이부분을 함수로 분리할 수 있을까요?

2021-01-20 23:49 UTC, dongwooklee96 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        } else {
저도 작성하면서 가독성이 좋지 않다고 느꼈는데 알려주셔서 감사합니다!
우선 함수 단위로 나누어서, 복잡해지지 않도록 해보겠습니다.

2021-01-20 23:51 UTC, dongwooklee96 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        }
음 저는 문자열을 '/' 로 구분해서 마지막 문자열을 찾는것이 문자열에서 앞에 것만 잘라내는 것과 같다고 생각했는데 혹시 차이를 알려주실 수 있으신가요?

2021-01-20 23:53 UTC, dongwooklee96 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +                this.statusCode = 200;
이 부분은 enum class를 통해서 구현해보려고 생각하고 있습니다.

2021-01-20 23:54 UTC, dongwooklee96 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +                }
좋은 생각입니다! 앞으로 코딩하면서 이런 부분은 주의하면서 코딩해야겠어요

2021-01-20 23:55 UTC, dongwooklee96 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +                this.statusCode = 200;
맞습니다. 이런 부분은 재사용할 수 있게 만드는 것이 좋겠습니다

2021-01-21 14:04 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +        }
코드를 읽을 때 `/`을 모두 찾아서 마지막의 숫자를 찾는 과정을 모두 이해해야 무엇을 하는 건지 이해를 할 수 있어요. 
의도가 마지막에 있는 `/`를 찾는 것이라면 사실 특정 문자열에서 마지막 `/`를 찾는 함수를 사용하면 더 의도가 드러날 수 있을 것 같아요. 예를들어 다음과 같이 해볼 수 있을 것 같아요.

```js
String path = "/tasks/10";
String id = path.substring(path.lastIndexOf("/") + 1); // 10
```

근데 사실 위의 해법도 완벽한 것이 아닌게 `/tasks/10/` 이런식으로 들어오면 안되긴 해요

2021-01-21 23:26 UTC, ahastudio commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +    int statusCode = 404;
특별한 이유가 없다면 둘 다 `private`일 것 같습니다.

2021-01-21 23:26 UTC, ahastudio commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +    int statusCode = 404;
HTTP Handler라는 관점에서, `statusCode`란 속성은 어떤 의미일까요? 지금은 객체의 속성이란 의미보다는 사실상 전역 변수란 의미로 쓰이는 것 같습니다.

2021-01-21 23:27 UTC, ahastudio commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +    }
이 생성자는 무엇을 하고 있는 건가요?

2021-01-22 23:32 UTC, dongwooklee96 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +    int statusCode = 404;
맞습니다!

2021-01-22 23:34 UTC, dongwooklee96 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +    }
다른 필드에서 객체 생성하는 것을 생성자에서 해줘야 할 것 같습니다.

2021-01-23 03:49 UTC, ahastudio commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +    }
`DemoHttpHandler` 객체는 이 프로그램에서 몇 개가 존재할까요? `Task` 객체는 이 프로그램에서 몇 개가 존재하게 될까요? 생성자에서 만든다는 건 어떨 결과를 초래할까요?

2021-01-23 17:53 UTC, hannut91 reviewed
handler를 사용하는 부분은 스프링을 사용하면 원활하게 될 것 같고 나머지는 전부 좋은 것 같아요 ㅎㅎ

테스트가 깨지는 곳이 있는데, 요구사항에 맞게 응답을 돌려주도록 해보면 어떨까요?

2021-01-23 17:53 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +            handleCollection(exchange, method);
`handle`이 계속 타고타고 들어가서 이 함수가 어떤 일을 처리하는지 파악하기 더 어려운 것 같아요. 너무 복잡하게 생각하실 필요는 없을 것 같아요 ㅎㅎ 스프링을 사용하게됐을 때 얼마나 단순하게 해결되는지만 보시면 좋을 것 같아요

2021-01-23 17:53 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/DemoHttpHandler.java
> +    }
`orElse`를 잘못사용하고 있는 것 같아요. Optional은 값이 있을수도 없을수도 있는 컨텍스트를 가진 값이에요. 이걸 사용하는 곳에게 전달하고 사용하는 곳에서 없을 경우 어떻게 처리할지 결정할 수 있어야 할 것 같아요

2021-01-24 14:06 UTC, merged

2021-01-24 14:07 UTC, hannut91 commented
고생하셨습니다 ㅎㅎ 다음 과제에서는 어떤 걸 중점적으로 학습할지 고민해보면 좋을 것 같아요.
그리고 요구사항에맞게 테스트를 모두 통과하도록 해보시면 더 좋을 것 같습니다!