[Spring 1주차 과제] ToDo REST API 만들기
CodeSoom/spring-week1-assignment-1 pull request #9
Opened 2021-01-18 21:08 UTC by developerOlive

🔖 TODO List 

🟩 ToDo 목록 얻기 - GET /tasks

🟩 ToDo 상세 조회하기 - GET /tasks/{id}

🟩  ToDo 생성하기 - POST /tasks

🟩 ToDo 제목 수정하기 - PUT/PATCH /tasks/{id}

🟩 ToDo 삭제하기 - DELETE /tasks/{id}

2021-01-19 11:48 UTC, developerOlive commented
🙏🏻 익숙치 않은 코드들이라 이해 및 공부를 위한 주석이 다소 많습니다. 
이해 부탁 드리며, 혹시 잘못 이해한 부분이 있다면 말씀 부탁 드립니다. :)

2021-01-19 14:14 UTC, developerOlive commented
위 커밋 중에
test와 Merge branch 'developerOlive' of ~ 커밋은
깃허브 조작 실수로 잘못 올라갔습니다. 양해 부탁드려요!

2021-01-19 14:51 UTC, hannut91 commented
커밋의 제목에는 왜 이 커밋을 작성했는지, 본문에는 그 것을 달성하기 위한 실제로 한 일을 적어주시면 좋습니다. 예를들어 `Task 클래스 생성`은 이유가 아니라 실제로 한 일입니다. 왜 Task 클래스를 생성했나요?

2021-01-19 14:56 UTC, hannut91 requested changes
고생하셨어요 ㅎㅎ

2021-01-19 14:56 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/App.java
> +            InetSocketAddress serverAddress = new InetSocketAddress(8282);
코드에서 Magic literal을 사용하고 있습니다. Magic literal이란 코드에서 단순한 숫자 혹은 문자열을 직접사용하는 것을 말합니다. 

예를들어서 수강 신청한 학생들이 있는데 신청한 학생들을 선착순 3명까지 자르기로 했습니다.

```js
const applicants = ['윤석', '수형', '기현', '기환', '아샬'];

// 강의를 들을 수 있는 최대 인원은 3명입니다.
const students = applicants.slice(0, 3);

console.log(students); // [ '윤석', '수형', '기현' ]
```

그래서 3명의 학생들이 걸러졌습니다. 하지만 코드만 보면 왜 3명이지? 4명이나 5명은 안되는지 알 수 없습니다. 주석을 달아서 설명했습니다. 딱히 문제는 없어보입니다. 하지만 만약 강의 정원을 늘리던지, 줄이면 주석도 수정해야하고 코드도 수정해야합니다. 

중복이 발생한 겁니다. 최악의 경우는 주석과 코드가 다를 경우 입니다. 테스트코드가 없다면 주석이 맞는건지 코드가 맞는건지 아무도 판별할 수 없습니다. 

그렇다면 주석없이 같은 표현을 하려면 어떻게 해야할까요?

```js
const LECUTRE_LIMIT = 3;

const applicants = ['윤석', '수형', '기현', '기환', '아샬'];

const students = applicants.slice(0, LECUTRE_LIMIT);

console.log(students); // [ '윤석', '수형', '기현' ]
```

Magic literal을 표현하는 상수를 만들면 됩니다. 이러면 주석이 없어도 왜 3명인지, 지원자들을 자를 때 무엇을 기준으로 자르는지 의도가 바로 드러납니다.

그렇다고 해서 모든 텍스트를 상수로 분리해야 하는 것은 아닙니다. 때로는 그냥 텍스트를 보여주는 것이 오히려 더 이해가 쉬울 수 있어요.

See also
  - https://refactoring.com/catalog/replaceMagicLiteral.html

2021-01-19 14:56 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/App.java
> +            HttpServer httpServer = HttpServer.create(serverAddress,0);
```suggestion
            HttpServer httpServer = HttpServer.create(serverAddress, 0);
```

코드 포맷팅을 습관화 하시면 좋을 것 같습니다. 저는 저장될 때 마다 포맷팅 되게 해놨어요

2021-01-19 14:56 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +
여기 빈 줄이 두 줄이 들어가있네요. 다른 의도가 있는 걸까요?

2021-01-19 14:56 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +    }
함수의 이름이 `jsonToTask`이니까 변수의 이름이 `json`을 받는게 자연스러운 것 같아요
```suggestion
    private Task jsonToTask(String json) throws JsonProcessingException {

        // content(내용)를 가지고와서 task의 클래스로 변환
        return objectMapper.readValue(json, Task.class);
    }
```

2021-01-19 15:39 UTC, developerOlive commented on app/src/main/java/com/codesoom/assignment/App.java
> +            HttpServer httpServer = HttpServer.create(serverAddress,0);
피드백 보고 바로 플러그인 설치했습니다 :) 유용한 거 알려주셔서 감사해요!

2021-01-19 15:41 UTC, developerOlive commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +
다른 의도가 없었습니다! 한 줄 이어야 되는데 두 줄을 띄운 것 같습니다!

2021-01-19 15:44 UTC, developerOlive commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +    }
동감합니다! 수정했습니다. :)

2021-01-20 15:15 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/HttpRequestInfo.java
> +public class HttpRequestInfo {
특정 개념에 대한 정보를 나타내기 때문에 `Info`라는 이름을 붙이신 것 같습니다. `Info`라는 것은 사실 아무런 의미를 드러내지 않습니다. 없어도 이해하는데 전혀 방해가 되지 않아요. 더 본질적으로 이 개념이 나타내는 것이 무엇인가에 대해서 더 고민해보는게 좋을 것 같습니다.

2021-01-20 15:15 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/HttpRequestInfo.java
> +    }
Template literal같은 것을 사용하면 더 좋겠지만... 없으니 `String.format`을 사용해보는 것은 어떨까요?

```Java
String.format("method=%s, path=%s, body=%body', method, path, body");
```

Template literal을 지원하는 코틀린이었다면 다음과 같이 사용할 수 있었을 거에요

```Kotlin
"method=${method}, path=${path}, body=${body}"
```

2021-01-20 15:15 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +        }
부정문은 한 번 더 생각해야되서 대부분의 경우 긍정문을 사용하는게 좋습니다.

2021-01-20 15:15 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +        if (!httpRequestInfo.getBody().isBlank()) {
`httpRequestInfo.hasBody` 이런건 어떨까요?

2021-01-20 15:15 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +        }
객체지향 생활체조에서는 들여쓰기를 오직 한 단계를 제한하고 else를 사용하지 말 것을 권장합니다.

See also
  - https://developerfarm.wordpress.com/2012/01/27/object_calisthenics_3/

2021-01-20 15:15 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +}
코드 마지막 줄에는 빈 줄이 하나가 추가되어야 합니다. 그렇지 않으면 위와 같이 GitHub에서 표시가 되고 또한 eslint에서 통과하지 못합니다. 

![image](https://user-images.githubusercontent.com/14071105/105195149-adcf0f80-5b7d-11eb-9cd1-38abf1e49195.png)
```suggestion
}

// 블라블라
```
이 것이 문제가 되는 이유는 POSIX 표준에서 Line을 “개행 문자로 끝나는 0개 이상의 개행 문자가 아닌 문자들의 시퀀스”으로 정의하고 있기 때문입니다.

```js
console.log('Hello');
```
만약 위와 같이 빈 줄이 없는 코드에서 아래에 코드를 추가하게 되면 Git은 다음과 같이 표시합니다.

```js
- console.log('Hello');
+ console.log('Hello');
+ console.log('world!');
```
저는 단순히 아래 한 줄만 추가했는데 왜 세줄이 변경되었다고 나오는 걸까요? 그 이유는 줄바꿈 문자 \n가 들어갔기 때문입니다. 

```js
- console.log('Hello');
+ console.log('Hello');\n
+ console.log('world');
```
만약 미리 빈 줄을 하나 추가한 상태에서 아래에 새로운 코드를 작성할 경우에는 다음과 같이 보여집니다.

```js
+ console.log('world');
```

이미 \n이 추가되어 있기 때문이죠. 따라서 코드 마지막 줄에 빈 줄 하나를 항상 추가해주는게 좋습니다.

2021-01-20 17:37 UTC, developerOlive commented on app/src/main/java/com/codesoom/assignment/HttpRequestInfo.java
> +public class HttpRequestInfo {
네! 일단은 HttpRequest로 수정하고 다시 한 번 생각해보겠습니다!

2021-01-20 18:03 UTC, developerOlive commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +        if (!httpRequestInfo.getBody().isBlank()) {
hasBody가 더 나은 것 같습니다. :) 수정했습니다!

2021-01-20 18:10 UTC, developerOlive commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +        }
적용해 보겠습니다!

2021-01-21 14:11 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +    }
path를 `/tasks/`로 분리해서 나머지를 얻을려고 하신 것 같아요. 주어진 문자열에서 찾아서 지워도 같은 결과를 얻을 수 있을 것 같아요.

```java
String path = "/tasks/12";
path.replace("/tasks/", ""); // 12
```

2021-01-21 14:11 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/TaskRepository.java
> +        newTask.setId(sequence++);
sequence의 값을 하나 증가시키고, 증가하기 전의 값을 id로 설정하는 것 같아요. 지금 두 가지 일을 한 줄에서 처리하고 있어서 이해하기 조금 어려운 것 같아요. 차라리 나눠서 작성하는게 이해하기 더 쉬울거에요

```
newTask.setId(sequence);
sequence = sequence + 1;
```

2021-01-22 07:08 UTC, developerOlive commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +    }
넵! 말씀하신대로 수정해 보았습니다!

2021-01-22 07:15 UTC, developerOlive commented on app/src/main/java/com/codesoom/assignment/TaskRepository.java
> +        newTask.setId(sequence++);
동감합니다! 추천해주신 대로 수정해 보았습니다!

2021-01-22 13:04 UTC, ahastudio commented on app/src/main/java/com/codesoom/assignment/JSONConverter.java
> + */
Javadoc 스타일을 따른다면 주석의 별 모양은 다음과 같이 됩니다.

```java
/**
 * JSON 데이터 처리와 관련된 메서드를 관리하기 위한 클래스.
 */
```

2021-01-22 13:05 UTC, ahastudio commented on app/src/main/java/com/codesoom/assignment/JSONConverter.java
> +    private static ObjectMapper objectMapper = new ObjectMapper();
`static`은 객체를 객체로 쓸 수 없게 만드는 주범 중 하나입니다. 구글에서 `static is evil` 등을 검색해 보세요.

2021-01-22 13:07 UTC, ahastudio commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +                        content = JSONConverter.tasksToJSON(TaskRepository.getTaskStore());
위에서 `new`로 객체를 만들었는데 그냥 `static`을 쓰고 있네요.

2021-01-22 13:09 UTC, ahastudio commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +                        GETAllTaskList();
PascalCase(대문자로 시작하는 camelCase)라서 코드를 읽는 사람은 이 부분이 클래스를 잘못 쓴 건지 어떤 상황인지 약간 망설이게 됩니다. 코딩 컨벤션을 따르면 불필요한 오해를 줄일 수 있습니다.

2021-01-22 13:10 UTC, ahastudio commented on app/src/main/java/com/codesoom/assignment/TaskRepository.java
> +    public static Map<Long, Task> getTaskStore() {
https://github.com/CodeSoom/spring-week1-assignment-1/pull/9#discussion_r562617211

2021-01-22 13:12 UTC, ahastudio commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +                    if (PUTUpdateTaskTitle(httpRequest)) {
리턴이 어떤 의미인지 추측하기 어렵습니다. 여기서는 예외를 활용하는 게 좋습니다.

2021-01-22 13:13 UTC, ahastudio commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +                    if (DELETETask(httpRequest)) { // id가 있고 정상적일 때
리턴을 추측할 수 없기 때문에 불필요한 주석이 쓰였습니다. 만약 `TaskNotFound` 같은 예외를 썼다면 코드만으로도 의미가 충분히 전달될 수 있었을 겁니다.

2021-01-22 14:30 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/App.java
> +            InetSocketAddress serverAddress = new InetSocketAddress(8000);
포트번호를 상수로 추출하면 좋을 것 같아요

2021-01-22 14:30 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/HttpRequest.java
> +        return "method=" + method + ", path=" + path + ", body=" + body;
`String.format`을 사용해봐도 좋을 것 같아요 ㅎㅎ

2021-01-22 14:30 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +        if (!httpRequest.hasMethod().isEmpty()) {
`method`가 비어있는 경우 빠르게 함수를 종료하는게 좋을 것 같아요. 그러면 코드를 읽는 사람은 더 이상 비어있는 경우에 대해서 생각할 필요가 없게됩니다.

2021-01-22 14:30 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +                    Long id = getIdFromPath(httpRequest);
`httpRequest`에서 `id`를 얻어온다는 것이 이해하기 어렵네요. 어떻게 하면 path 파라미터를 가져온다는 것을 의도를 드러낼 수 있을까요?

2021-01-22 14:30 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +                    findOne(id);
이 코드는 아무런 일을 하고 있지 않은 것 같아요. 어디에 쓰이는건가요?

2021-01-22 14:30 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +        }
중복 처리가 되고 있는 것 같아요 위에서 이미 `else`로 확인하고 있는 부분인 것 같아요

2021-01-23 06:29 UTC, developerOlive commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +}
넵 알겠습니다!

2021-01-23 06:34 UTC, developerOlive commented on app/src/main/java/com/codesoom/assignment/JSONConverter.java
> + */
앗 네! 알려주신대로 수정했습니다 :)

2021-01-23 06:57 UTC, developerOlive commented on app/src/main/java/com/codesoom/assignment/JSONConverter.java
> +    private static ObjectMapper objectMapper = new ObjectMapper();
확인해보겠습니다!

2021-01-23 06:58 UTC, developerOlive commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +                        content = JSONConverter.tasksToJSON(TaskRepository.getTaskStore());
피드백 확인 후 JSONConverter 클래스에 있는 메서드에서 static 키워드를 제외시켰습니다.
그리고 MyHttpHandler에서도 static이 아닌 new 객체 사용해서 JSONConverter 메서드에 접근하는 것으로 코드 변경하겠습니다!

2021-01-23 07:05 UTC, developerOlive commented on app/src/main/java/com/codesoom/assignment/TaskRepository.java
> +    public static Map<Long, Task> getTaskStore() {
static 키워드 제외하고 new로 객체 만들어서 접근하는 방식으로 수정했습니다!

2021-01-23 07:26 UTC, developerOlive commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +                        GETAllTaskList();
일부 대문자로 시작하는 메서드명 -> 소문자로 시작하도록 수정하였습니다!

2021-01-23 10:08 UTC, developerOlive commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +                    if (DELETETask(httpRequest)) { // id가 있고 정상적일 때
` case "DELETE":
                    if (deleteTask(httpRequest.getId())) {
                        content = jsonConverter.tasksToJson(taskRepository.getTaskStore());
                        response(HTTP_OK, content, exchange);
                        break;
                    }
                    if (httpRequest.getId().equals(notFoundId)) {
                        response(HTTP_NOT_FOUND, content, exchange);
                        break;
                    }`
위와 같이 수정해 보았습니다!

2021-01-23 10:12 UTC, developerOlive commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +                    Long id = getIdFromPath(httpRequest);
```suggestion
                    // tasks/{id}를 입력했을 경우 (입력한 아이디에 해당하는 할일만 보여줌)
                    Long id = httpRequest.getId();
                    findOne(id);
                    content = jsonConverter.taskToJson(findOne(id));
                    response(HTTP_CREATED, content, exchange);
                    break;
```
위와 같이 수정해 보았습니다! 피드백 주신 의도에 맞게 수정한 것인지 확인 부탁 드리겠습니다 :)

2021-01-23 12:12 UTC, developerOlive commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +                    findOne(id);
```suggestion
                    /* /tasks/{id}를 입력했을 경우 (입력한 아이디에 해당하는 할 일만 가져오는 경우) */
                    Long id = httpRequest.getId();
                    content = jsonConverter.taskToJson(findTaskById(id));
                    response(HTTP_OK, content, exchange);
                    break;
```

findOne(id); 코드는 잘못 적은것 같습니다! 위와 같이 수정해 보았습니다.

2021-01-23 12:15 UTC, developerOlive commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +        }
넵 삭제했습니다!

2021-01-23 12:35 UTC, developerOlive commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +        if (!httpRequest.hasMethod().isEmpty()) {
네! 메서드가 비어있는 조건문을 먼저 적는 방향으로 수정했습니다!

2021-01-23 12:36 UTC, developerOlive commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +        }
if (httpRequest.hasMethod().length() >= minimunMethodLength) {
            switch (httpRequest.hasMethod()) {
                case "GET":

2021-01-23 12:37 UTC, developerOlive commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +        if (!httpRequest.hasMethod().isEmpty()) {
```suggestion
        if (httpRequest.hasPath().isEmpty()) {
            response(HTTP_NOT_FOUND, content, exchange);
        }

        if (httpRequest.hasMethod().length() >= minimunMethodLength) {
```
위와 같이 수정해보았습니다!

2021-01-23 12:49 UTC, developerOlive commented on app/src/main/java/com/codesoom/assignment/App.java
> +            InetSocketAddress serverAddress = new InetSocketAddress(8000);
넵 추출하였습니다!

2021-01-23 13:09 UTC, developerOlive commented on app/src/main/java/com/codesoom/assignment/HttpRequest.java
> +        return "method=" + method + ", path=" + path + ", body=" + body;
수정했습니다!

2021-01-23 13:37 UTC, developerOlive commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +                    if (PUTUpdateTaskTitle(httpRequest)) {
![image](https://user-images.githubusercontent.com/67456294/105579708-6d64d100-5dcb-11eb-8062-63868aea4dd5.png)

위와 같이 수정해 보았는데 혹시 피드백 주신 의도에 맞지 않다면 말씀 부탁 드립니다!
만약, 피드백 주신 의도와 맞지 않다면
"여기서는 예외를 활용하는 게 좋습니다." 라는 부분을 좀 더 풀어서 설명해 주실 수 있을까요?

2021-01-23 16:55 UTC, ahastudio commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +                    if (PUTUpdateTaskTitle(httpRequest)) {
이 코드는 `can-`이란 이름을 통해서 물어볼 것처럼 하지만 사실은 뭔가를 다 처리하고 그 결과를 돌려줍니다. 우리는 그 이름에 속게 되죠. “Can I help you?”라고 묻길래 “No”라고 답하려고 했더니 이미 자기 멋대로 하고 있었다 같은 상황이 됩니다.
여기서는 같은 메서드를 두번이나 실행하기 때문에 어떤 문제가 발생할 가능성도 배제할 수 없습니다. 지금은 우연히 큰 문제가 없지만, 만약 결제 같은 기능이었다면 큰 문제가 되겠죠.
이 코드는 우리는 리턴 값이 무엇인지, 정확히 무슨 일이 벌어지는지 계속해서 추측해야 쓸 수 있습니다. 그렇지 않도록 해야 하죠.

이렇게 두 가지 질문을 던져보면 좋습니다.

1. 우리가 원하는 것은 무엇인가?
2. 무엇이 잘못될 수 있는가?

Java는 위의 코드를 이렇게 표현할 수 있습니다.

```java
try {
    // 1. 내가 원하는 건 Task의 제목을 갱신하는 거다.
    updateTaskTitle(httpRequest);

    content = ....;
    response(HTTP_OK, content, exchange);
} catch (TaskNotFound e) {
    // 2. Task를 찾을 수 없는 문제가 발생할 수 있군!!!!!
    content = ....;
    response(HTTP_NOT_FOUND, content, exchange);
}
```

2021-01-23 16:57 UTC, ahastudio commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +                    if (DELETETask(httpRequest)) { // id가 있고 정상적일 때
https://github.com/CodeSoom/spring-week1-assignment-1/pull/9#discussion_r563174055

2021-01-23 18:13 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +                        response(HTTP_NOT_FOUND, content, exchange);
`response`가 응답을 보내는 함수였군요. 정해진 메서드가 없는 경우에는 응답을 아에 보내지 않아서 hanging 될 것 같아요

2021-01-23 18:13 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +
이 함수에 `exchange`를 받은 다음에 `exchange`의 메서드인 `sendResponseHeaders`를 다시 호출하고 있어요. `response`의 역할이 무엇인지 잘 모르겠어요

2021-01-23 18:13 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +                    if (httpRequest.hasPath().equals("/tasks")) {
`hasPath`를 위에서 한 번 밑에서도 한 번 호출하고 있는 것 같아요. `path`를 가지고 있는 변수 하나를 선언해서 사용하는 것은 어떨까요?

2021-01-23 18:13 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +                        getAllTaskList();
`get`하는데 아무것도 받는 곳이 없어요. 함수의 반환타입이 `void`라는 것은 사이드 이펙트가 있다는 것을 의미하는데, `get`이 사이드 이펙트가 있을 것이라고 예상하는 사람은 아무도 없을거에요 ㅎㅎ

2021-01-23 18:13 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +                        response(HTTP_OK, content, exchange);
위의 선언된 `content`를 직접 변경하며 재사용하고 있는 것 같아요. 변수를 선언한 곳과 사용한 곳의 거리가 멀면 좋지 않습니다. 위에서 사용한 변수를 재사용하기 보다는 새로운 변수를 사용하는게 더 좋을 것 같아요.
근데 그렇게 되면 이름이 같아서 다시 고민이 되겠죠?

2021-01-23 18:13 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +                    content = jsonConverter.taskToJson(findTaskById(id));
`find`하는 것은 무엇가로부터 찾고 있는 것인데, 찾는 다는 행위는 항상 없는 경우가 있을 것 같아요.

2021-01-23 18:13 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +                    content = postCreateNewTask(httpRequest);
새로운 task를 만드는데 파라미터로 httpRequest를 넘기는게 이해하기 어려운 것 같아요. 새로운 task를 만든 다면 task를 만드는데 필요한 무언가를 넣는 것처럼 보여야 할 것 같아요. 그리고 지금은 새로운 것을 만들고 기존의 테스트케 추가하는 것이니 이름도 다르게 될 것 같아요. 예를들면 다음과 같이 보이는 모습이 자연스러울 것 같아요.

```java
Task task = new Task(title);
tasks.add(task);
String content = jsonConverter.taskToJSON(task);
response(HTTP_CREATED, content, exchange);
```

2021-01-23 18:13 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +    }
메서드의 이름이 이미 `delete`라는 이름이 들어가 있으니 파라미터의 이름은 그냥 `id`로 해도 이해하기 쉬울 것 같아요

2021-01-23 18:13 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/TaskRepository.java
> +    }
`null`이 나올 수 있을거에요

2021-01-24 12:47 UTC, developerOlive commented on app/src/main/java/com/codesoom/assignment/MyHttpHandler.java
> +                    if (PUTUpdateTaskTitle(httpRequest)) {
"여기서는 예외를 활용하는 게 좋습니다."  라는 피드백 부분이
적어주신 코드를 보고서야 드디어 이해가 되었습니다!
잘 기억해서 활용한다면 훨씬 좋은 코드가 될 것 같습니다.
예시 들어주셔서 감사합니다!

2021-01-24 14:12 UTC, merged

2021-01-24 14:12 UTC, hannut91 commented
고생하셨습니다 ㅎㅎ 작은것 하나하나도 제대로 배울려고 하시는 모습이 인상적이네요 ㅎㅎ 아쉬운 점은 테스트 요구사항에 대해서 아직 정확히 파악하지 못하신 것 같아요. 다음과제에서는 요구사항에 맞게 모든 테스트를 통과시키면 좋을 것 같습니다 고생하셨어요!